src/test/java/OlgaSafMenuStartPageTest.java

Created test Menu Start and a new class

US_200_001 | Start

---

src/test/java/CheckTableMenuTopListsTest.java

Check table name test added

---

src/test/java/CountLanguagesStartNumbersMaksPtTest.java

added testNamesStartNumbersLanguages
https://trello.com/c/NCFpW8q2/20-at300001-browse-languages-0-9-count-languages

created class CountLanguagesStartNumbersMaksPtTest

---

src/test/java/Song99BottlesAsTest.java

Song99BottlesAsTest first practice test

Song99BottlesAsTest 

---

src/test/java/pages/LyricsPage.java
src/test/java/pages/MainPage.java
src/test/java/pages/StartPage.java
src/test/java/tests/CheckTableMenuTopListsTest.java
src/test/java/tests/CountLanguagesStartNumbersMaksPtTest.java
src/test/java/tests/FirstTest.java
src/test/java/tests/OlgaSafMenuStartPageTest.java
src/test/java/tests/ShurikGSubmitNewLanguageTest.java
src/test/java/tests/ShurikGTest.java
src/test/java/tests/Song99BottlesAsTest.java
src/test/java/tests/Song99BottlesServachakMTest.java

https://trello.com/c/T4FTc6Sd/37-at100001-structuremainpagestartpagelyricspage-create-packages-and-pages-mainpage-startpage-lyricspage

AT_100.001 | [Structure][MainPage][StartPage][LyricsPage] | Create packages and pages MainPage, StartPage, LyricsPage

---

src/test/java/pages/LyricsPage.java
src/test/java/pages/MainPage.java
src/test/java/tests/LessonsTest.java

https://trello.com/c/V6hoO2zL/40-at100003-mainpage-verify-h1-header-is-99-bottles-of-beer

AT_100.003 | [MainPage] | Verify H1 header is 99 Bottles of Beer

---

src/test/java/tests/Song99BottlesElenaNov686Test.java

Song99bottlesElenaNov686test class added

Song99bottlesElenaNov686test

---

src/test/java/tests/SharingLanguageByReddit.java

AT_300.011 | [Browse Language] | Sharing Language A+

added test AT_300.011 | [Browse Language] | Sharing Language A+

---

src/test/java/pages/TeamPage.java

https://trello.com/c/y4mLbfkP/47-at200001-teampage-create-page-teampage

AT_200.001 | [TeamPage] | Create page TeamPage

---

src/test/java/pages/MainPage.java
src/test/java/tests/AnaLamaFooterMenuBarButtonsTest.java

"Locator FooterMenuBar added, 2 methods added"
https://trello.com/c/ywEr8Txu/53-at100004-mainpage-footer-verifyfootermenubarbuttons

AT_100.004 [MainPage]| Footer| VerifyFooterMenuBarButtons

---

src/test/java/pages/StartPage.java
src/test/java/tests/TatianaPTest.java

https://trello.com/c/EEiusMsN/56-at200002-startfind-start-menu-locator

AT_200.002\Start Find Start Menu Locator

---

src/test/java/pages/StartPage.java

https://trello.com/c/Wv5wGMvt/60-rf200002-startfind-start-menu-locator

RF_200.002 | [Start][Find Start Menu Locator]

---

src/test/java/pages/AbcPage.java

https://trello.com/c/bPCodajD/58-at300001-structurebrowse-languages-menu-create-abcpage

AT_300.001 | [Structure][Browse Languages Menu] | Create AbcPage

---

src/test/java/pages/MainPage.java
src/test/java/tests/Song99BoutleXbrookxTest.java

https://trello.com/c/9Gr3z1zF/73-at300006-mainpage-find-browse-languages-menu-locator

AT_300.006 | [MainPage] Browse languages menu locator

---

src/test/java/pages/AbcPage.java

created getCategoryJ(), created getCategoryJClick().
https://trello.com/c/GVWezucO/72-at300004-browse-languages-abc-j-verify-description-page

AT_300.004 | Abc | created WebDriver, created Xpath CATEGORY_J,

---

src/test/java/pages/TopListRealPage.java

AT_500.005 | [Structure] | [TopListRealPage] | Create page TopListRealPage

---

src/test/java/tests/TeamTest.java

https://trello.com/c/hvEbA383/66-at200004-teampage-verify-h3-team-names-of-the-creators-of-the-site-is-oliver-schade-gregor-scheithauer-stefan-scheler

AT_200.004 | [TeamPage] | Verify H3 Team names of the creators of the site is "Oliver Schade, Gregor Scheithauer, Stefan Scheler"

---

src/test/java/pages/JPage.java
src/test/java/pages/MPage.java

https://trello.com/c/S34zI1P9/86-at300008-structurempage-create-page-mpage-and-webdriver
And Refactor getDescriptionCategoryJ().getText();(commit 7079282)
RF_300.005 [AbcPage][JPage] | getDescriptionCategoryJText()
https://trello.com/c/w5DMtFji/87-rf300005-abcpagejpage-getdescriptioncategoryjtext

At 300.008 structure m page create page m page and web driver

---

src/test/java/pages/AbcPage.java

https://trello.com/c/epiqqSoi/88-rf300006-abcpage-getcategoryjclick

Refactor AbcPage - getCategoryJClick() RF_300.006

---

src/test/java/pages/TopListRealPage.java
src/test/java/tests/CheckTableMenuTopListsTest.java

RF_500_003 | Top Lists | Top Rated Real | Check table name + added methods and locator in TopListRealPage

---

src/test/java/tests/Song99BoutleXbrookxTest.java

https://trello.com/c/XUPhdu1V/68-at300003-abcpage-verify-table-header-is-language-author-date-comments-rate

AT_300.003 | [AbcPage] | Verify table header is Language, Author, Date, Comments, Rate

---

src/test/java/pages/MainPage.java

https://trello.com/c/uwn4pCME/93-rf100001-mainpage-create-locator-submitnewlanguage-and-methods-getsubmitnewlanguagemenu-getsubmitnewlanguagemenutext

RF_100.001/CreateLocatorAndMethods

---

src/test/java/pages/MainPage.java
src/test/java/tests/MorigorProjectAllTest.java

added locator and methods getH2Header() and getH2HeaderText() in package MainPage, created MorigorProjectAllTest, added testVerifyTextOnMainPage()
https://trello.com/c/REfQWaml/101-at100005-main-h2-header-verify-text

AT_100.005 | Main | H2 Header | Verify Text

---

src/test/java/tests/WarningImportantInSubmitNewLanguagePageTest.java

https://trello.com/c/H6fTQtam/115-at700003-submitnewlanguagepage-warning-important

AT_700.003 warning IMPORTANT

---

src/test/java/pages/SignGuestbookPage.java

https://trello.com/c/gEiesP3p/117-at600004-structuresignguestbookpage-create-page-signguestbookpage

AT_600.004 | [Structure][SignGuestbookPage] | Create page SignGuestbookPage

---

src/test/java/pages/AbcPage.java

Added LocatorCATEGORY_M in AbcPage
Added Methods getCategoryM() and getCategoryMClick() in AbcPage
https://trello.com/c/XD3cg3C5/84-at300007-browse-languages-abcpagempage-last-language-is-mysql

AT_300.007_AbcPage

---

src/test/java/pages/MPage.java

Added Locator LAST_LANGUAGE in MPage
Added Methods getLastLanguageInM() and getLastLanguageInMText() in MPage
https://trello.com/c/XD3cg3C5/84-at300007-browse-languages-abcpagempage-last-language-is-mysql

AT_300.007_AbcPage_MPage_CreateLocatorsAndMethods

---

src/test/java/pages/MainPage.java

https://trello.com/c/hUnNqKX2/109-rf100002mainpage-create-locator-submitsearchlanguages-footersearchlanguages-and-methods-getsubmitsearchlanguagesmenu-getsubmitse

RF_100_002|[MainPage] | Create locator SUBMIT_SEARCH_LANGUAGES, FOOTER_SEARCH_LANGUAGES and methods 2

---

src/test/java/pages/SearchPage.java

https://trello.com/c/ucb8b6nK/81-at400003-structuresearchpage-create-page-searchpage

AT_400.003 |[Structure][SearchPage] | Create page SearchPage

---

src/test/java/tests/MaksPtTest.java

| Last language is MySQL.
Added testLastLanguageInM() in class MaksPtTest
https://trello.com/c/XD3cg3C5/84-at300007-browse-languages-abcpagempage-last-language-is-mysql

AT_300.007 | Browse Languages | [AbcPage][MPage]

---

src/test/java/pages/HistoryPage.java

https://trello.com/c/5lcZgF2M/61-at200003-starthistorycreate-history-locator

AT_200.003 [Start][History]|Create Locator

---

src/test/java/pages/MPage.java

XPATH LAST_LANGUAGE after conflict

Refactoring MPage (add getLastLanguageInMText(), getLastLanguageInM(),

---

src/test/java/pages/SearchPage.java

https://trello.com/c/n7H7ZK7D/59-at400002-search-languages-create-locators-and-methods-for-the-test-veryfi-title-search-languages

AT_400.002 | [Search Languages] | Create locators and methods for the test Veryfi title Search Languages

---

src/test/java/pages/MainPage.java
src/test/java/tests/KononirinIrinaShTest.java

https://trello.com/c/qlwQVE4d/91-at100004-mainpage-verify-last-item-of-menu-is-submit-new-language

Correct method on MainPage, create testLastItemMenuIsSubmitNewLanguage

---

src/test/java/pages/HistoryPage.java

https://trello.com/c/EhTz3cn0/131-at200009-structure-start-history-add-locators-and-methods

AT_200.009 | Structure| Start | History| Add locators and methods

---

src/test/java/tests/MorigorProjectAllTest.java

https://trello.com/c/7JZnU0RD/113-at600003-guestbook-sign-guestbook-error-message

AT_600.003 | Guestbook | Sign Guestbook | Error_Message

---

src/test/java/tests/NadiaLidtTest.java

https://trello.com/c/KpnPjww9/120-at400004-search-languages-new-search-veryfi-title-search-languages

AT_400.004 | [Search Languages] | New search | Veryfi title Search Languages

---

src/test/java/pages/StartPage.java

https://trello.com/c/gclexvlH/132-at200010-start-add-historicinformationlink-locator-add-methods-gethistoricinformationlink-and-gethistoricinformationlinkclick

AT_200.010/START locator added, methods created

---

src/test/java/pages/LanguageMathematicaPage.java
src/test/java/pages/MPage.java
src/test/java/tests/GalaKonTests.java

New class is created, BRENTON_BOSTICK locator is moved to new class, M_PAGE locator is deleted.

RF_300.009 | [Structure][Browse Languages] | [MPage] | Author of Mathematica Language

---

src/test/java/tests/AuthorOfMathematicaLanguageTest.java

AT_300.030 | [Browse Languages] | [MPage] | Author of Mathematica Language

add testAuthorOfMathematicaLanguage

---

src/test/java/tests/AnufryievaTest.java

https://trello.com/c/XZJdTs8X/140-at300013browse-languagespage-j-check-title

AT_300.013[BROWSE LANGUAGES][Page J] | Check title

---

src/test/java/tests/SvetlanaGTest.java

https://trello.com/c/65cS6DLt/92-at200007-start-text-information-about-website-historic-information-link

AT_200.007/START/TestVerifyHistoricInformationLink

---

src/test/java/pages/SignGuestbookPage.java

https://trello.com/c/5gNmaTQJ/110-at600002-guestbook-sign-guestbook-verification

AT_600.002 | Guestbook | Sign Guestbook | Verification

---

src/test/java/tests/Song99BottlesEkaterinaKazakovaTest.java

please verify my 99bottles tests and mark for approval.

Song99BottlesEkaterinaKazakovaTest created

---

src/test/java/pages/ImpressumPage.java

OBakatova/AT_200.005.01 [Start ] [Privacy Menu] [Impressum] | Created  ImpressumPage

OBakatova/AT_200.005.01 Created ImpressumPage

---

src/test/java/pages/ImpressumPage.java
src/test/java/tests/CheckSubmenuPrivacyTest.java

OBAkatova/AT_200.005.02 [Start ] [Privacy Menu] [Impressum]|Check Submenu Start/Privacy IsClickable

OBakatova/AT 200.005.02 check submenu start/privacy clickable

---

src/test/java/pages/StartPage.java

https://trello.com/c/AVIIL2b2/152-at200013-structure-start-add-locator-for-link-here

START/Add Locator for Link Here Add Methods

---

src/test/java/tests/LessonsTest.java

US - https://trello.com/c/XwT1dIuv/161-us200009-start-lyrics-verify-text-of-the-song-99-bottles-of-beer
AT - https://trello.com/c/czpSF9ek/164-at200009-mainstartlyrics-verify-text-of-the-song-99-bottles-of-beer

AT_200.009 | [Lyrics] Verify text of the song 99 Bottles of Beer

---

src/test/java/pages/StartPage.java

US - https://trello.com/c/0joggwJM/165-us200010-start-create-locator-menusonglyrics-create-method-clickmenusonglyrics
AT - https://trello.com/c/Sg6WOIEv/169-at200010-start-create-locator-menusonglyrics-create-method-clickmenusonglyrics

AT_200_010 [Start] Create locator SONG_LYRICS_MENU, create methods getMenuSongLyrics() and  clickMenuSongLyrics()

---

src/test/java/pages/LyricsPage.java

US - https://trello.com/c/YAA5miMd/167-us200011-startlyrics-create-locator-for-tags-p-create-method-methods-to-get-a-text-from-tags-p
AT - https://trello.com/c/dQtDnEmz/168-at200011-startlyrics-create-locator-for-tags-p-create-method-methods-to-get-a-text-from-tags

AT_200_011 [Start][Lyrics] Create locator for tags p, create method/methods to get a text from tags

---

src/test/java/pages/LyricsPage.java
src/test/java/tests/LessonsTest.java

RF - https://trello.com/c/r9fgVKD4/170-rf200004-lyrics-testsonglyricstext-to-pom

RF_200.004 [Lyrics] testSongLyricsText() to POM

---

src/test/java/tests/CheckMenuStartHeader2Test.java

https://trello.com/c/XdN3VS1E/176-at200015-startheader2

CheckMenuStartHeader2Test_AT_200.015 | Start|Header2

---

src/test/java/pages/MainPage.java
src/test/java/pages/SubmitNewLanguagePage.java

https://trello.com/c/IY7ey9lD/160-rf700001-structuremainpage-submitnewlanguagepage-spelling-error-message

RF_700.001 | [Structure][MainPage] [SubmitNewLanguagePage] | Spelling Error Message

---

src/test/java/pages/SearchPage.java

https://trello.com/c/36I0wU9V/181-at400006-search-languagescreate-search-box-locator

AT_400_006[ Search Languages]Create Search Box Locator

---

src/test/java/pages/MainPage.java
src/test/java/pages/StartPage.java

https://trello.com/c/wviP4eLC/4-rf000000-class-name-test-name

RF_200.006 [Start Page] [Main Page] Moving Start Menu Locator 

---

src/test/java/pages/TopListPage.java

AT - https://trello.com/c/GZhnb17R
US - https://trello.com/c/gv2m9r5e

AT_500.006 | [Structure] | [TopList] | Create page Top Lists and WebDriver, create locator for TopListRealPage

---

src/test/java/pages/MainPage.java

AT- https://trello.com/c/jvd4dPOh

AT_100.006 [Main] Create locator TopListMenu, create method clickTopListMenu()

---

src/test/java/pages/MainPage.java
src/test/java/tests/CheckTableMenuTopListsTest.java

RF - https://trello.com/c/lMvE8d9L

RF 500.004/top list real page test table name menu top lists submenu top rated real to POM

---

src/test/java/pages/AbcPage.java
src/test/java/pages/LPage.java
src/test/java/tests/LiliYnusovaTest.java

https://trello.com/c/zoFMYVDT/189-at300014-browse-language-l-page-check-header

AT_300.014 | [Browse Language] | [L Page] | Check header

---

src/test/java/pages/HistoryPage.java
src/test/java/pages/StartPage.java
src/test/java/tests/TatianaPTest.java

https://trello.com/c/dN4PEY8s/182-rf200005-historypage-delete-history-menu-locator

RF_200.005[ HistoryPage] |Move History Menu Locator

---

src/test/java/pages/SubmitNewLanguagePage.java

RF_700.002_Structure_SubmitNewLanguagePage_GetFieledCategory.click
https://trello.com/c/xkQ1pSdK

RF_700.002_Structure_SubmitNewLanguagePage_GetFieledCategory | click

---

src/test/java/tests/KsSignGuestbookPageTest.java

AT_600.006 | KsSignGuestbookPageTest testSecurityCodeField

AT_600.006_|_KsSignGuestbookPageTest_testSecurityCodeField

---

src/test/java/pages/StartPage.java

RF_200.007 |Start Page| History_Menu locator refactor

RF_200.007 |Start Page| History_Menu locator refactor

---

src/test/java/tests/TatianaPTest.java

https://trello.com/c/uyu2zyrK/185-at200016-start-pagetest-history-menu-on-start-page

AT_200.016 | Start Page|Test History Menu on Start Page

---

src/test/java/tests/NadiaLidtTest.java

https://trello.com/c/PrXB6IG4/13-us700001-submit-new-language-submit-language-button-error-message
https://trello.com/c/TO5jeZ9T/187-at700005-submit-new-languagespelling-error-message

AT_700.005 | [Submit New Language] | Spelling Error Message

---

src/test/java/tests/Song99BottlesAsTest.java

AT_700.006| Submit New Language| submitNewLanguageCategoryTest
https://trello.com/c/FvGZUxjZ

AT_700.006| Submit New Language| submitNewLanguageCategoryTest

---

src/test/java/pages/SignGuestbookPage.java

https://trello.com/c/v849LeiH/197-us600007-mainpage-create-locator

added locator GUESTBOOK

---

src/test/java/pages/SignGuestbookPage.java
src/test/java/tests/KsSignGuestbookPageTest.java

https://trello.com/c/v849LeiH/197-us600007-signguestbookpage-create-locator-guestbook

added metod getGuestbookMenu

---

src/test/java/pages/SearchPage.java

https://trello.com/c/cZZfM814/204-at400007-search-pagecreate-submitsearch-button-locator

AT_400.007 | Search Page|Create 'submitsearch' Button Locator

---

src/test/java/pages/TopRatedRealPage.java

https://trello.com/c/G8kg9MCg/207-us500008-create-topratedrealpage

added class TopRatedRealPage

---

src/test/java/pages/TopListTopHitsPage.java

https://trello.com/c/ofhfqcSU/208-us500009-top-lists-top-hits-creat-page-top-hits-and-webdriver-create-locator-for-tophits

TopListTopHitsPage|US_500_009|Top Lists|Top Hits|Creat page Top Hits and WebDriver,create locator for TopHits

---

src/test/java/tests/TopListTest.java

https://trello.com/c/qf9S3sEw/202-at500007-kstoplist-gotothetopratedtest

added test testGoToTheTopRated

---

src/test/java/tests/AnaLamaFooterMenuBarButtonsTest.java

US - https://trello.com/c/WJEJ1CR5/51-us100004-main-footer
AT - https://trello.com/c/B4teVb6T/63-at100004002-mainpage-footer-testbrowselanguagebutton

AT_100.004.002 | [MainPage] Footer | TestBrowseLanguageButton

---

src/test/java/pages/Guestbook.java
src/test/java/pages/MainPage.java

https://trello.com/c/Kfzif5Hx/236-rf100003-menu

RF_100_003 |[MainPage] | Create locator GUESTBOOK_ and [GuestbookPage]

---

src/test/java/pages/HistoryPage.java

AT - https://trello.com/c/2W8kHTs3/239-at200015-start-history-create-the-locators-and-methods
US - https://trello.com/c/smlUNlbu/192-us200015-start-history-create-the-locators-and-methods

AT_200.015 | [Start] [History] Create the locators and methods

---

src/test/java/tests/SvetlanaGTest.java

https://trello.com/c/QqqhX4va/151-at200012-start-verify-link-here

AT_200.012/START/testVerifyHereLink created

---

src/test/java/tests/TopListTest.java

https://trello.com/c/LD2ho9Y7/214-at500010-kstoplisttest-testgotothetopratedreallanguages

added testGoToTheTopRatedRealLanguages

---

src/test/java/pages/TopListAssemblyPage.java
src/test/java/pages/TopListPage.java

https://trello.com/c/NYdrqtRr/234-us500016-top-lists-create-locator-toplistassemblymenu-create-the-toplistassemblypage

Create locator TOP_LIST_ASSEMBLY_MENU, Create the topListAssemblyPage

---

src/test/java/pages/TopListPage.java

US_500_017 | [Top Lists] | Create locator TOP_LIST_TOPHITS_MENU

Create locator TOP_LIST_TOPHITS_MENU and metods

---

src/test/java/tests/IreneSnitkoTests.java

AT - https://trello.com/c/Oetnnt0Z/243-at200014-start-history-verify-the-code-of-basic-in-text
US - https://trello.com/c/UfH4qwMx/191-us200014-start-history-verify-the-code-of-basic-in-text

AT_200.014 | [Start] [History] Verify the code of BASIC in text

---

src/test/java/pages/TopListNewLanguagesThisMonthPage.java
src/test/java/pages/TopListPage.java

https://trello.com/c/jezAA20J/245-us500018-top-lists-create-locator-toplistassemblymenu-create-the-toplistassemblypage

added new class TopListNewLanguagesThisMonthPage

---

src/test/java/tests/OlgaSafMenuStartPageTest.java

US. - https://trello.com/c/ZvWItv3i/232-us300015-structurebrowse-languages-abcpage-submenu-c
AT. - https://trello.com/c/ls3uRfar/252-at300017-browse-languages-abcpage-submenu-c

AT_300.017| |[MainPage][Browse Languages] [AbcPage][CPage]

---

src/test/java/pages/TopListEsotericPage.java

https://trello.com/c/OFvMhVse/249-us500019-toplistesotericpage-create-locator-h2tablenameesoteric-and-metods

create locator H2_TABLE_NAME_ESOTERIC and metods

---

src/test/java/pages/HistoryPage.java

https://trello.com/c/CItxCHRO/258-rf200008-starthistory-locator-and-method-added

Locator LOCAL_COPY added and method getLocalCopyLink

---

src/test/java/pages/HistoryPage.java
src/test/java/tests/CheckLocalCopyLinkTest.java

AT  https://trello.com/c/FNCry8TX/255-at20000201-start-history-check-local-copy-link
US https://trello.com/c/ssZk8mJz/15-us200002-start-history

At 200 002 01/start history check local copy link

---

src/test/java/pages/AbcPage.java

AT -https://trello.com/c/XzWItMiv

AT_300.020/AbcPage created locator and methods for submenu 0-9

---

src/test/java/pages/TopListPage.java
src/test/java/pages/TopListTopHitsPage.java
src/test/java/tests/ViktroriiaKTest.java

RF_500.005 |Top Lists Top HitsPage | refactoring locator for TopHits

RF_500.005TopListsTopHitsPageRefactoringLocatorForTopHits

---

src/test/java/tests/BrowseLanguageSubmenuTest.java

AT - https://trello.com/c/XzWItMiv

AT_300.020/Verify that the first submenu in Browse Language is 0-9

---

src/test/java/pages/TopListAssemblyPage.java

US_500_020 | TopListAssemblyPage | create locator H2_TABLE_NAME _ASSEMBLY and metods

create locator H2_TABLE_NAME_ASSEMBLY and metods

---

src/test/java/pages/WPage.java

AT-https://trello.com/c/ML6iWu3p/267-at300021structurewpagecreate-page-wpage-and-webdriver
US-https://trello.com/c/0YSo6jSY/265-us300021structurewpagecreate-page-wpage-and-webdriver

AT_300.021/StructureWPageCreatePageWPageAndWebDriver

---

src/test/java/pages/AbcPage.java

AT - https://trello.com/c/1yUJA23h
US - https://trello.com/c/xt2dP1oX

AT_300.022/Created locator and method for AllCategories in Browse language

---

src/test/java/pages/JPage.java

US - https://trello.com/c/Cfom5g3R/256-us300018-browse-language-j-create-the-locator-for-tags-a-and-method-for-get-number-programming-languages
AT - https://trello.com/c/eGoq4yCB/268-at300018-browse-language-j-create-the-locator-for-tags-a-and-method-for-get-number-programming-languages

AT_300.018 [Browse Language] [J] Create the locator for tags a and method for get number programming languages

---

src/test/java/tests/BrowseLanguageSubmenuTest.java

AT - https://trello.com/c/1yUJA23h

AT_300.022/Browse Languages | How Many Categories In Browse Language

---

src/test/java/tests/TopListTest.java

AT_500.011 | KsTopListTest | testGoToTheTopRatedEsotericLanguages

AT_500.011 | KsTopListTest | testGoToTheTopRatedEsotericLanguages

---

src/test/java/pages/StartPage.java

https://trello.com/c/CYFFblOh/273-at200017start-create-locator-menuteam-create-method-clickmenuteam

AT_200.017 locator menuTeam and method getTeamMenuClick created

---

src/test/java/tests/TopListTest.java

https://trello.com/c/Ve7SMiXZ/216-at500012-kstoplisttest-testgotothetopratedassemblylanguages

testGoToTheTopRatedAssemblyLanguages added

---

src/test/java/tests/OlgaSafMenuStartPageTest.java

US  -  https://trello.com/c/ISaYmHQi/23-us500001-top-list-top-rated-menu-toplist
AT  -  https://trello.com/c/xiFtVeaW/253-at500016-mainpagetoplistpage-toplist-assembly

AT_500.016 | [MainPage][TopListPage] | Toplist Assembly

---

src/test/java/tests/Song99BottlesTimurKhusTest.java

testSongLyricsText was created

testSongLyricsText created

---

src/test/java/pages/AbcPage.java

https://trello.com/c/sr0USzHh/277-at300019-structurebrowse-languagesabcpage-create-category-p

AT_300_019 | [Structure][Browse Languages][AbcPage] | Create Category P

---

src/test/java/tests/IreneSnitkoTests.java

AT - https://trello.com/c/2YIFj74L/285-at300025-browse-language-j-%D1%81heck-that-the-number-of-programming-languages-is-22
US - https://trello.com/c/ZVmDwQDd/250-us300017-browse-language-j-%D1%81heck-that-the-number-of-programming-languages-is-22

AT_300.025 [Browse Language] [J] Сheck that the number of programming languages is 22

---

src/test/java/pages/AbcPage.java

https://trello.com/c/Y0VRbtzP/213-at300014-structure-abc-page-r-page-locator-r-page-method-click

AT_300.014/CategoryR Locator, method getCategoryRClick created

---

src/test/java/pages/JPage.java
src/test/java/pages/LanguageJava3Page.java
src/test/java/tests/Song99BoutleXbrookxTest.java

https://trello.com/c/uMSO7mjs/290-at300024-main-browse-languagesjpagelanguagejava3page-verify-count-versions-of-java-languages

AT_300.024 | [Main] [Browse Languages][JPage][LanguageJava3Page] | Verify count versions of Java languages

---

src/test/java/tests/BrowseLanguageJavaTest.java

US - https://trello.com/c/Qerp6LYh/300-us300027-abc-j-languagejava3-verify-that-the-object-oriented-version-has-the-most-comments-for-java-language
AT - https://trello.com/c/gBco1AoT/303-at300027-abc-j-languagejava3-verify-that-the-object-oriented-version-has-the-most-comments-for-java-language

AT_300.027 | ABC | J | LanguageJava3 | Verify that the “object-oriented version” has the most comments for Java language

---

src/test/java/pages/JPage.java
src/test/java/tests/Song99BoutleXbrookxTest.java

https://trello.com/c/W2yKJzFO/311-rfjpagerename-method-getgetjavalanguageclick

RF|[JPage]Rename method getGetJavaLanguageClick()

---

src/test/java/pages/SignV2Page.java
src/test/java/tests/KsSignGuestbookPageTest.java
src/test/java/tests/MorigorProjectAllTest.java

to Signv2Page
Сlasses changed for refactoring:
KsSignGuestbookPageTest
MorigorProjectAllTest
https://trello.com/c/qlkkp2LU/310-rf600001-structuresignv2page-change-name-signguestbookpage-to-signv2page

RF_600.001 | [Structure][Signv2Page] | Change name SignGuestbookPage

---

src/test/java/pages/TopListPage.java

https://trello.com/c/rey40MsE/306-us500021-top-lists-create-locator-toplistnewcommentsmenu

US_500.021 | [Top Lists] | Create locator NEW_COMMENTS_MENU

---

src/test/java/pages/LPage.java

AT_300.011 | LPage | add locator Category L | creat method clickCategoryL

AT_300.011LPageAddlocatorCategoryLcreatMethodCclickCategoryL

---

src/test/java/tests/BrowseLanguagesAllCategoriesOfSubmenuTest.java

https://trello.com/c/31PklXDR/282-at300024-browselanguages-allcategoriesofsubmenubrowselanguages

AT_300_024| BrowseLanguages | AllCategoriesOfSubmenuBrowseLanguages

---

src/test/java/pages/RPage.java

https://trello.com/c/KVHlvXJR/299-at300031-r-page-create-page-and-web-driver

AT_300.031/Page R and driver created

---

src/test/java/tests/VerifyPythonInfoLinkTest.java

AT -https://trello.com/c/8eXIzidj/284-at300020-mainbrowse-languagesabcpageppagelanguagepythonpage-check-python-info-link
US -https://trello.com/c/CGSxwPDx/278-us300020-languagepythonpage-verify-python-info-link
TC -https://trello.com/c/9ualvOsI/279-tc300020-mainbrowse-languagesabcpageppagelanguagepythonpage-verify-python-info-link

AT_300_020 [Main][Browse languages][AbcPage][PPage][LanguagePythonPage] | Verify Python Info Link

---

src/test/java/pages/LPage.java

AT_300.012 | LPage | add locator Language l33t| creat method clickLanguage l33t

addLocatorLanguageL33tCreatMethodClickLanguageL33t

---

src/test/java/pages/TopListPage.java

US_500.021 | [Top Lists] | Create locator NEW_COMMENTS_MENU and metods

fixed metod

---

src/test/java/pages/GuestbookV2Page.java
src/test/java/tests/Guestbook_ReadGuestbook_LastPage_08AlimDuiL_Test.java

GuestbookV2Page
Сlass changed for refactoring:
Guestbook_ReadGuestbook_LastPage_08AlimDuiL_Test
https://trello.com/c/f4hJxfxH/326-rf600002-structureguestbookv2page-change-name-guestbook-to-guestbookv2page

RF_600.002 | [Structure][GuestbookV2Page] | Change name Guestbook to

---

src/test/java/pages/SignV2Page.java

[GuestbookV2Page][SignV2Page] | Verify error text
https://trello.com/c/bZfayY6k/325-at600010-guestbookv2pagesignv2page-verify-error-text
locators: 
NAME_FIELD;
LOCATION_FIELD;
EMAIL_FIELD;
CAPTCHA_FIELD;
COMMENT_FIELD;
Methods: 
getNameField()
inputNameField(String name)
getLocationField()
inputLocationField(String name)
getEmailField()
inputEmailField(String name)
inputHomepageField(String name)
getCaptchaField()
inputCaptchaField(String name)
getCommentField()
inputCommentField(String name)

Created locators and methods in SignV2Page for the AT_600.010

---

src/test/java/pages/GuestbookV2Page.java

AT_600.010 | [GuestbookV2Page][SignV2Page] | Verify error text
locator: SIGN_GUESTBOOK
Methods: getSignGuestbook(), SignGuestbookClick()
https://trello.com/c/bZfayY6k/325-at600010-guestbookv2pagesignv2page-verify-error-text

Create locator and methods in GuestbookV2Page

---

src/test/java/pages/RPage.java

https://trello.com/c/1eZ1AhZI/332-at300035-structure-abc-page-r-page-locator-trtags-method-count-languages

AT_300.035/RPageLocatorTRTAGSMethodGetTRTagsMethodCountLanguages

---

src/test/java/tests/MaksPtTest.java

https://trello.com/c/bZfayY6k/325-at600010-guestbookv2pagesignv2page-verify-error-text

AT_600.010 | [GuestbookV2Page][SignV2Page] | Verify error text

---

src/test/java/pages/SignV2Page.java

and method getErrorMessageTagFont()
https://trello.com/c/hhTKOvQO/333-at600011-guestbookv2pagesignv2page-verify-error-text-font

AT_600.011 SignV2Page add Locator TAG_FONT_ERROR_TEXT

---

src/test/java/tests/Song99BottlesKononirinIrinaShTest.java

https://trello.com/c/ZfoaTYUO/341-rf200009-lyrics-testsonglyricstext-to-pom

RF_200.009 [Lyrics] testSongLyricsText() to POM

---

src/test/java/pages/TopListTopHitsPage.java

US_500.022 | [TopListTopHitsPage] | Create locator H2_TABLE_NAME_TOP_HITS and metods

H2_TABLE_NAME_TOP_HITS create

---

src/test/java/pages/LanguageJava3Page.java
src/test/java/tests/GalaKonTests.java

https://trello.com/c/cCe4kpcq/343-at300030-browse-languages-language-java-verify-amount-of-comments-in-object-oriented-version-test
1. The test with current locator and method is written and added to new PR.

AT_300.030 | Browse Languages | Language Java | Verify amount of comments in object-oriented version Test

---

src/test/java/tests/TopListTest.java

https://trello.com/c/e8ngcJLU/217-at500013-toplisttest-testgotothetophits

AT_500.013 | TopListTest | testGoToTheTopHits

---

src/test/java/pages/SignV2Page.java

https://trello.com/c/GRgZ9cYl/342-at600012-guestbookv2pagesignv2page-verify-error-text-background-color

AT_600.012 [SignV2Page] create method getErrorMessageAttributeStyle()

---

src/test/java/pages/LanguageJavascript1948Page.java

US - https://trello.com/c/J3wWPmQd/321-us300034-structure-languagejavascript1948page-create-languagejavascript1948page-and-webdriver
AT - https://trello.com/c/rAS97p7h/323-at300034-structure-languagejavascript1948page-create-languagejavascript1948page-and-webdriver

AT_300.034 [Structure] [LanguageJavascript1948Page] Create LanguageJavascript1948Page and WebDriver

---

src/test/java/tests/MorigorProjectAllTest.java

testVerificationOfHomepageAttribute() added
US   https://trello.com/c/xZ6RoWsf/108-us600002-guestbookv2signv2-verification-of-homepage-attribute
AT   https://trello.com/c/34JBUnYy/144-at600002-guestbookv2signv2-verification-of-homepage-attribute

AT_600.002 [Guestbookv2][Signv2] Verification of Homepage Attribute

---

src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/riKvFuh1/263-at200016-start-history-click-on-the-first-picture
https://trello.com/c/Ddr34pqp/246-us200016-start-history-the-first-picture

AT_200.016StartHistoryClickOnTheFirstPicture

---

src/test/java/tests/CheckGeneralFieldsOnGuestbook.java

US_600.013 | Guestbook | Sign guestbook | Check all input fields

add tests: check general fields on guestbook page

---

src/test/java/tests/SvetlanaGTest.java

https://trello.com/c/I0iMi9vn/305-at300033-abc-page-r-page-count-languages

AT_300.033/RPage testPageRCountLanguages created

---

src/test/java/pages/AbcPage.java

https://trello.com/c/lysMuG34/340-rf300000-abcpage-test-name

RF_300.010 | AbcPage| CATEGORY_Z

---

src/test/java/pages/TopListNewLanguagesThisMonthPage.java

https://trello.com/c/EjdCTLpA/345-us500023-toplistnewlanguagesthismonthpage-create-locator?filter=member:user98971337

US_500.023 | [TopListNewLanguagesThisMonthPage]> create locator

---

src/test/java/pages/JPage.java

AT - https://trello.com/c/m68ZruoU/361-rf300011-browse-language-j-refactor-method-countprogramminglanguages

RF_300.011 [Browse Language] [J] Refactor method countProgrammingLanguages()

---

src/test/java/tests/TatianaPTest.java

AT_400_001 | Search Languages | Search | Search java |

AT_400_001 | Search Languages | Search | Search java |

---

src/test/java/pages/StartPage.java
src/test/java/tests/StartPageWishesTeamTest.java

Test
https://trello.com/c/pxHHYtuS/94-at200008-start-text-information-about-the-website-wishes-from-the-team
US
https://trello.com/c/Xyq369YP/344-us200008-start-text-information-about-the-website-verify-wishes-from-the-team
https://trello.com/c/5rwBz2IT/328-at200021-start-text-information-about-the-website-wishes-from-the-team-create-locator-and-methods

At 200.008/start text information about website wishes from team

---

src/test/java/pages/AbcPage.java

https://trello.com/c/37dtAzmO/351-atbrowse-languagesabccreate-locators-and-methods-upageviktoriiakarpus

 ATBrowseLanguageAbcClickUPageViktoriiaKarpus

---

src/test/java/pages/UPage.java

https://trello.com/c/7gCcjfoI/387-atabc-pagecreate-upageviktoriiakarpus

ATAbcPageCreateUPageViktoriiaKarpus

---

src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/8dmcWf30/389-atmainpageabcpagefind-in-submenu-letter-uviktoriiakarpus

ATMainPageAbcPageFindInSubmenuLetterUViktoriiaKarpus

---

src/test/java/pages/MainPage.java

US https://trello.com/c/ZZxgJXna/374-us100007-main-create-locator-for-footer-menu-submit-new-language
AT  https://trello.com/c/0ZdIRpBm/375-at100007-main-create-locator-for-footer-menu-submit-new-language

AT_100.007 [Main] Create locator for footer menu Submit New Language

---

src/test/java/pages/MainPage.java
src/test/java/pages/SubmitNewLanguagePage.java

US  https://trello.com/c/F2QYs1qi/383-us700007-submitnewlanguagepage-create-the-locators-and-methods
AT  https://trello.com/c/rnO4eO1Z/384-at700007-submitnewlanguagepage-create-the-locators-and-methods

At 700.007/submit new language page create the locators and methods

---

src/test/java/pages/MainPage.java

US   https://trello.com/c/oLWdYGy5/391-us100008-main-create-methods-for-footer-menu-submit-new-language
AT  https://trello.com/c/cTJpLSEO/392-at100008-main-create-methods-for-footer-menu-submit-new-language

AT_100.008 [Main] Create getFooterSubmitNewLanguage() and getFooterSubmitNewLanguageClick() for footer menu Submit New Language

---

src/test/java/pages/AbcPage.java

US - https://trello.com/c/sPUVclE0/371-usabcpagemaintable-create-locator-for-tags-th-create-method-to-get-a-header-table-from-tags-hr
AT - https://trello.com/c/qhU3Fl3S/390-atabcpagemaintable-create-locator-for-tags-th-create-method-to-get-a-header-table-from-tags-hr

[AT][AbcPage][main][table] Create locator for tags th, create method to get a header table from tags hr

---

src/test/java/tests/NadiaLidtTest.java

US - https://trello.com/c/ocYzGMkZ/399-usbrowse-languager-page-verify-information-about-language-rpg-iv-free-form
AT - https://trello.com/c/7YScyUz0/401-atabc-pager-page-verify-information-about-language-rpg-iv-free-form

[AT][Abc Page][R Page] Verify Information About Language RPG IV Free Form (NadiaLidt)

---

src/test/java/pages/UPage.java

https://trello.com/c/xBnNJiiI/396-atabc-pageupagecreate-locator-tableu-and-method-countlanguagesuviktoriiakarpus

ATAbcPageUPageCreateLocatorTABLEUAndMethodCountLanguagesUViktoriiaKarpus

---

src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/138DMCrI/395-atabc-pageupagecount-languagesviktoriiakarpus

ATAbcPageUPageCountLanguagesViktoriiaKarpus

---

src/test/java/pages/AbcPage.java

https://trello.com/c/H4hiqRGM/403-tcabc-pagecreate-locator-submenucategories-and-method-getsubmenucategoriesgalakon

[Abc Page]Create Locator SUBMENU_CATEGORIES and Method getSubmenuCategories

---

src/test/java/pages/AbcPage.java
src/test/java/pages/MainPage.java
src/test/java/tests/AnaLamaFooterMenuBarButtonsTest.java
src/test/java/tests/AnufryievaTest.java
src/test/java/tests/AuthorOfMathematicaLanguageTest.java
src/test/java/tests/BrowseLanguageJavaTest.java
src/test/java/tests/BrowseLanguageSubmenuTest.java
src/test/java/tests/BrowseLanguagesAllCategoriesOfSubmenuTest.java
src/test/java/tests/GalaKonTests.java
src/test/java/tests/Guestbook_ReadGuestbook_LastPage_08AlimDuiL_Test.java
src/test/java/tests/HelenVelTest.java
src/test/java/tests/IreneSnitkoTests.java
src/test/java/tests/LiliYnusovaTest.java
src/test/java/tests/MaksPtTest.java
src/test/java/tests/NadiaLidtTest.java
src/test/java/tests/OlgaSafMenuStartPageTest.java
src/test/java/tests/Song99BoutleXbrookxTest.java
src/test/java/tests/StartPageWishesTeamTest.java
src/test/java/tests/SvetlanaGTest.java
src/test/java/tests/TatianaPTest.java
src/test/java/tests/TitleAndDescriptionJPageTest.java
src/test/java/tests/VasiliySinTest.java
src/test/java/tests/VerifyPythonInfoLinkTest.java
src/test/java/tests/ViktroriiaKTest.java
src/test/java/tests/СompareLinksSearchLanguagesTest.java
src/test/java/tests/СompareRealLinksSearchLanguages.java

RF - https://trello.com/c/Kmh1WfCA/406-rfstructureabcpagemainpage-refactoring-abcpage-and-mainpage-rom-t

[RF][Structure][AbcPage][MainPage] Refactoring AbcPage and MainPage

---

src/test/java/pages/SubmitNewLanguagePage.java

Refactoring  https://trello.com/c/BA4GypXj/409-rf700002-submit-new-language-refactoring-method-gettitleh2click

RF_700.002 [Submit New Language] refactoring method getTitleH2Click()

---

src/test/java/pages/LanguageJava3Page.java
src/test/java/tests/GalaKonTests.java
src/test/java/tests/Song99BoutleXbrookxTest.java

RF - https://trello.com/c/QNmaEA8R/410-rfstructurelanguagejava3page-refactoring-languagejava3page-rom-t

[RF][Structure][LanguageJava3Page] Refactoring LanguageJava3Page

---

src/test/java/pages/SubmitNewLanguagePage.java

RF  https://trello.com/c/FT20Vps1/412-rf700003-submit-new-language-refactoring-method-gettitleh2click

RF_700.003 [Structure][Submit New Language] refactoring method getTitleH2Text()_Morigor

---

src/test/java/pages/AbcPage.java
src/test/java/tests/GalaKonTests.java

https://trello.com/c/N7ke8EEC/415-atabc-pageverify-submenu-textgalakon
1. The test for verifying SUBMENU text with new locatoe and new method is created.

[AT][Abc Page]Verify SUBMENU text

---

src/test/java/pages/InfoPage.java
src/test/java/pages/MainPage.java
src/test/java/pages/StartPage.java
src/test/java/tests/CheckLocalCopyLinkTest.java
src/test/java/tests/HelenVelTest.java
src/test/java/tests/IreneSnitkoTests.java
src/test/java/tests/LessonsTest.java
src/test/java/tests/Song99BottlesKononirinIrinaShTest.java
src/test/java/tests/StartPageWishesTeamTest.java
src/test/java/tests/SvetlanaGTest.java
src/test/java/tests/TatianaPTest.java
src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/iHyLzzbT/411-rfstructurestartpagemainpagerefactoring-startpagemainpagedmswlpk

[RF][Structure][StartPage][MainPage]Refactoring StartPage,MainPage<dmswlpk>

---

src/test/java/tests/NadiaLidtTest.java

US - https://trello.com/c/O1REd53C/302-usabcpagemaintable-%D1%81hecktableheaders?filter=member:nadialidt
AT - https://trello.com/c/PxUbTdUG/398-atabcpagemaintable-%D1%81hecktableheaders

[AT][AbcPage][main][table] СheckTableHeaders <NadiaLidt>

---

src/test/java/pages/SubmitNewLanguagePage.java
src/test/java/tests/NadiaLidtTest.java
src/test/java/tests/Song99BottlesAsTest.java
src/test/java/tests/VasiliySinTest.java
src/test/java/tests/WarningImportantInSubmitNewLanguagePageTest.java

[RFSubmitNewLanguagePageAsel]
https://trello.com/c/RpET5fl3

RFSubmitNewLanguagePageAsel

---

src/test/java/pages/APage.java

[US][Structure][ AbcPage ][A Page] Created APage
[AT][Structure][ AbcPage ][A Page] Created Locator H2<Safronova Olga>

[AT][Structure][ AbcPage ][A Page] Created Locator H2

---

src/test/java/tests/OlgaSafMenuStartPageTest.java

[AT][A][main][header][h2] Verify the Text Submenu A Title

At amainheaderh2 verifythe text submenu a title

---

src/test/java/pages/JPage.java
src/test/java/tests/AnufryievaTest.java
src/test/java/tests/BrowseLanguageJavaTest.java
src/test/java/tests/GalaKonTests.java
src/test/java/tests/IreneSnitkoTests.java
src/test/java/tests/MaksPtTest.java
src/test/java/tests/Song99BoutleXbrookxTest.java
src/test/java/tests/TitleAndDescriptionJPageTest.java

RF - https://trello.com/c/Tbsy5d0S/407-rfstructurerefactoring-jpageirenesnitko

[RF][Structure]Refactoring JPage<IreneSnitko>

---

src/test/java/tests/CheckDownloadText.java

AT_300.013 | LPage | Test Download Sourse Language l33t - 
https://trello.com/c/QyZupC7d/320-at300013-lpage-test-download-sourse-language-l33t?filter=member:arailymashimova1

ad testDownloadSourceLanguageL33t

---

src/test/java/pages/ZPage.java

[US][Structure][ZPage] Create locators and methods:
https://trello.com/c/QrMVFvSG/336-usstructurezpage-create-locators-and-methods
[AT][Structure][ZPage] Create locators and methods :
https://trello.com/c/XrPsi5bI/339-at300036-abc-z-create-page-abczpage

[AT][Structure][ZPage] Create locators and methods

---

src/test/java/pages/SearchPage.java
src/test/java/tests/NadiaLidtTest.java
src/test/java/tests/TatianaPTest.java

RF - https://trello.com/c/6qDtajFl/435-rfstructuresearchpage-refactoring-methods-and-values-names-nadialidt

[RF][Structure][SearchPage] Refactoring Method's and Value's names <NadiaLidt>

---

src/test/java/pages/MainPage.java
src/test/java/pages/SearchPage.java
src/test/java/tests/NadiaLidtTest.java
src/test/java/tests/TatianaPTest.java

https://trello.com/c/BwtrrmRD/436-rfstracturemainsearch-searchmenu-refactoring-dmswlpk

[RF][Stracture][Main][Search] Search_Menu refactoring <dmswlpk>

---

src/test/java/tests/CheckCssOfInactiveStatus.java

https://trello.com/c/k3ncKcER/438-at200018-atteammaintext-check-css-of-inactive-status

add method testCssOfInactiveStatus

---

src/test/java/pages/LanguageAlgol60Page.java

https://trello.com/c/lOLyRssn/444-usstructureabcpage-a-pagecreated-language-algol-60
https://trello.com/c/esAfkZIL/445-atstructureabcpage-a-pagecreated-language-algol-60safronova-olga

[AT][Structure][AbcPage ][A Page]Created Language Algol 60

---

src/test/java/tests/CountCommentOfLanguageShakespeare.java

https://trello.com/c/A0acuoqT/442-at000000-atsmaintabletr-count-comments-language-shakespeare-arailymasar

 add testCountCommentOfLanguageShakespeare

---

src/test/java/pages/LanguageAlgol60Page.java

https://trello.com/c/MmurLjoI/426-us-abcpage-a-pagelanguage-algol-60maintablelink
https://trello.com/c/2IK2myL2/443-atabcpage-a-pagelanguage-algol-60maintablelinksafronova-olga

[AT][AbcPage ][A Page][Language Algol 60][main][table][link] Methods

---

src/test/java/pages/JPage.java

US - https://trello.com/c/JmZL2qI5/451-usjpage-create-methods-for-testirenesnitko
AT - https://trello.com/c/EsmF5f91/452-atjpage-create-methods-for-testirenesnitko

[AT][JPage] Create methods for test<IreneSnitko>

---

src/test/java/tests/Song99BottlesAsTest.java

test Get Error Message Invalid Sec Code 
https://trello.com/c/cpd71Hxm

[AT][Submit New Language]get Error Message Invalid Security Code| Asel.A

---

src/test/java/tests/BrowseLanguagesZSubmenuTest.java

[US][Z][main][All]
https://trello.com/c/QrMVFvSG/336-uszmainall
[TC][Z][main][header][h2] Verify text
https://trello.com/c/JPZ4YgAd/449-tczmainheaderh2-verify-text
[AT][Z][main][header][h2] Verify text
https://trello.com/c/Aug7ZT3s/433-atzmainheaderh2-verify-text

[AT][Z][main][header][h2] Verify text

---

src/test/java/pages/TeamPage.java
src/test/java/tests/AAA_MenuTeamTest.java

Refactored class TeamPage
Add new test Class
https://trello.com/c/xAMGp3HU/448-atstartnavigationsubmenuteam-verifytext

[AT][Start][navigation][submenu][team] VerifyText

---

src/test/java/pages/GuestbookV2Page.java
src/test/java/tests/Guestbook_ReadGuestbook_LastPage_08AlimDuiL_Test.java
src/test/java/tests/MaksPtTest.java

https://trello.com/c/168V5sfH/456-rfstructureguestbookv2page-refactoring-guestbookv2page-makspt
Locators changed:
GUESTBOOK_V2_SUBMENU
SIGN_V2_SUBMENU
Methods changed:
getGuestbookV2
getSignV2
clickSignV2

[RF][Structure][GuestbookV2Page] Refactoring GuestbookV2Page <MaksPt>

---

src/test/java/pages/RPage.java

https://trello.com/c/QWrBG8ui/461-atstructurer-add-locator-h2-add-locator-ptagtext-add-methods-gettextsvetlanag1011

AT_StructureRPageAddLocatorsAndMethods

---

src/test/java/pages/TopListPage.java
src/test/java/tests/CheckTableMenuTopListsTest.java
src/test/java/tests/OlgaSafMenuStartPageTest.java
src/test/java/tests/TopListTest.java
src/test/java/tests/ViktroriiaKTest.java

RF - https://trello.com/c/D3QXw0Sd

[RF][Structure][TopListPage] Refactoring locators/methods/ServachakM

---

src/test/java/tests/AAA_MenuTeamTest.java

Add new test class testVerifyLinkText
https://trello.com/c/Q9H2AFCK/469-atstartnavigationsubmenuteam-verifylinktext-shurikgr

[AT][Start][navigation][submenu][team] VerifyLinkText

---

src/test/java/pages/SignV2Page.java

US - https://trello.com/c/1AArfEfq/472-ussignv2mainimages-icons-verify-five-messages-iconsirenesnitko
AT - https://trello.com/c/mbzXXECr/473-atsignv2mainimages-icons-create-methods-for-testirenesnitko

[AT][Signv2][main]images/icons] Create methods for test<IreneSnitko>

---

src/test/java/pages/SearchPage.java

https://trello.com/c/FzKWzYE4/471-atsearchpage-create-locator-and-methods-for-test-annaabg

[AT][SearchPage] Create locator and methods for test <AnnaAbg>

---

src/test/java/tests/OlgaSafMenuStartPageTest.java

https://trello.com/c/MmurLjoI/426-us-abcpage-a-pagelanguage-algol-60maintablelink
https://trello.com/c/lBqlRiLC/425-at-abcpage-a-page-verify-language-algol-60safronova-olga

[AT][ AbcPage ][A Page] Verify Language Algol 60

---

src/test/java/pages/AbcPage.java
src/test/java/pages/MPage.java

https://trello.com/c/601uJ9TC/474-rfbrowse-languagesabcpagempagegalakon
The name of locator for Language MySQL is changed and its xpath is rewrite.
Accordingly, the method for finding exact element in MPage and the tests for Language MyAQL Page are changed.

[RF][Browse Languages][AbcPage][MPage]

---

src/test/java/pages/LanguagePerl737Page.java

US - https://trello.com/c/BLW0PEF6/477-usstructurelanguageperl737page-create-languageperl737page-and-webdriver-annaabg
AT - https://trello.com/c/5CPiJzLr/478-atstructurelanguageperl737page-create-languageperl737page-and-webdriver-annaabg

[AT][Structure][LanguagePerl737Page] Create LanguagePerl737Page and Webdriver

---

src/test/java/tests/IreneSnitkoTests.java

US - [US][Signv2][main]images/icons] Verify five Message's icons
AT - https://trello.com/c/FDy0BrEA/483-atsignv2mainimages-icons-verify-the-attributes-src-of-messages-icons
+ reformat code of previous test's last lines

[AT][Signv2][main]images/icons] Verify the attributes src of Message's icons<IreneSnitko>

---

src/test/java/tests/AAA_MenuLyricsTest.java

[AT][Start][navigation][submenu][lyrics] VerifyText
https://trello.com/c/xST4i0E4/491-atstartnavigationsubmenulyrics-verifytext-shurikgr
[AT][Start][navigation][submenu][lyrics] VerifyLinkText
https://trello.com/c/XIoEvdNJ/493-atstartnavigationsubmenulyrics-verifylinktext-shurikgr
[AT][Start][navigation][submenu][lyrics] VerifyNavigation
https://trello.com/c/6Q83QD8a/494-atstartnavigationsubmenulyrics-verifynavigation-shurikgr

[US][Start][navigation][submenu][lyrics] 

---

src/test/java/pages/LanguagePerl737Page.java

[US] - https://trello.com/c/95Lxzb3J/485-uslanguageperl737page-create-locator-and-methods-annaabg
[AT] - https://trello.com/c/rsE6fhfU/492-atlanguageperl737page-create-locator-and-methods-annaabg

[AT][LanguagePerl737Page] Create locator and methods <AnnaAbg>

---

src/test/java/pages/InfoPage.java
src/test/java/tests/CheckLocalCopyLinkTest.java

RF - https://trello.com/c/jR3SuYpo/408-rfstructurehistorypagerefactoring-historypageirenesnitko

[RF][Structure][InfoPage]Refactoring InfoPage<IreneSnitko>

---

src/test/java/tests/VerifyPerlLanguageFeaturesTest.java

[US} -https://trello.com/c/gFPFWtur/496-uslanguageperl737pagemaintabletr-verify-perl-language-features-text-annaabg
[AT] -https://trello.com/c/00WN6nUw/498-atlanguageperl737pagemaintabletr-verify-perl-language-features-text-annaabg

[AT][LanguagePerl737Page][main][table][text] Verify Perl Language Features' Text <AnnaAbg>

---

src/test/java/tests/BrowseLanguageSubmenuTest.java

US - https://trello.com/c/Y6mjc6nq

[US][ABC][navigation][submenu][zero] Verify text, link text, navigation

---

src/test/java/tests/SvetlanaGTest.java

https://trello.com/c/V7Hrkv2y/466-atrmainheaderh2-verify-header-verify-p-text-svetlanag1011

[AT][R][main][header][h2] Verify Header Verify p Text

---

src/test/java/tests/Song99BoutleXbrookxTest.java

https://trello.com/c/I4xiV8kX/515-atstartnavigationsubmenuimpressum-verify-text-valentinkuprin

[AT][Start][navigation][submenu][impressum] Verify Text

---

src/test/java/pages/NewCommentsPage.java
src/test/java/tests/TatianaPTest.java

https://trello.com/c/9GrZqvPa/509-atnewcommentspagemain-verify-no-new-commentsdmswlpk

[AT][NewcommentsPage][main] Verify No New Comments<dmswlpk>

---

src/test/java/pages/ImpressumPage.java
src/test/java/pages/StartPage.java
src/test/java/tests/Song99BoutleXbrookxTest.java

https://trello.com/c/r0SOQuRo/521-atstartnavigationsubmenuimpressum-verify-link-text-valentinkuprin

[AT][Start][navigation][submenu][impressum] Verify Link Text

---

src/test/java/tests/NadiaLidtTest.java

US - https://trello.com/c/nsz3p1zg/532-usstartnavigationsubmenuinfo-veryfi-text-link-text-navigation
AT - https://trello.com/c/u8FQLfM8/536-atstartnavigationsubmenuinfo-veryfi-text-nadialidt

[AT][Start][navigation][submenu][info] Veryfi text <NadiaLidt>

---

src/test/java/tests/SubmitNewLanguageTest.java

https://trello.com/c/Wyi9XJ3z/542-atmainnavigationmenusubmitnewlanguage-verify-textsvetlanag1011

[AT][Main][navigation][menu][submitnewlanguage] Verify Text

---

src/test/java/pages/ZPage.java
src/test/java/tests/BrowseLanguagesZSubmenuTest.java

[RF][Structure][Zpage] fix bugs in methods
https://trello.com/c/twD9IWQt/533-rfstructurezpage-fix-bugs-in-methods
[AT][Z][main][table][th] Verify table headers
https://trello.com/c/ZQRLrPP5/529-atzmaintableth-verify-table-headers
Для теста пришлось сделать рефакторинг [Zpage], так как при его написании в секции цикла 2 методов проглядела и не исправила при копировании название метода.

[AT][Z][main][table][th] Verify table headers

---

src/test/java/tests/NadiaLidtTest.java

US - https://trello.com/c/up8Sn3te/534-usstartnavigationsubmenuinfo-veryfi-text-link-navigation
AT - https://trello.com/c/R3RSlXfp/544-atstartnavigationsubmenuinfo-veryfi-link-text

[AT][Start][navigation][submenu][info] Veryfi link text

---

src/test/java/pages/SubmitNewLanguagePage.java

US - https://trello.com/c/y7hvetE6/504-ussubmitnewlanguagepage-create-locator-and-method-for-test
AT - https://trello.com/c/YFzxb9b7/505-atsubmitnewlanguagepage-create-locator-and-method-for-test

[AT][SubmitNewLanguagePage] Create locator and method for test<IreneSnitko>

---

src/test/java/pages/KPage.java

https://trello.com/c/qyDsiidz/540-us300032-structure-create-k-page-create-web-driver-elements-methods

Create KPage Web Driver Elements Methods

---

src/test/java/tests/NadiaLidtTest.java

US - https://trello.com/c/up8Sn3te/534-usstartnavigationsubmenuinfo-veryfi-text-link-navigation
AT - https://trello.com/c/njvTyT0G/546-atstartnavigationsubmenuinfo-veryfi-navigation-nadialidt

[AT][Start][navigation][submenu][info] Veryfi navigation <NadiaLidt>

---

src/test/java/pages/NewCommentsPage.java
src/test/java/tests/TatianaPTest.java

https://trello.com/c/evOSerq0/537-atpage-nametask-namegithub-nickname

[AT][NewCommentsPage][main][header][h2]Verify text<dmswlpk>

---

src/test/java/pages/AbcPage.java
src/test/java/pages/TeamPage.java

1. US https://trello.com/c/wN3k5vEs/550-usteammainimageverify-imagesgalakon
2. TC https://trello.com/c/HlqpFZYa/551-tcteammainimageverify-imagesgalakon
3. AT https://trello.com/c/aMQ271C4/552-atteammainimageverify-imagesgalakon

[TC][Team][main][image]Verify images

---

src/test/java/tests/IreneSnitkoTests.java

US - https://trello.com/c/awpfBG6Y/553-ussubmitnewlanguagepage-verify-the-captchas-image
AT - https://trello.com/c/nWb1ZwaM/554-atsubmitnewlanguagepage-verify-the-attribute-src-of-captchairenesnitko

[AT][SubmitNewLanguagePage] Verify the attribute src of captcha<IreneSnitko>

---

src/test/java/tests/SubmitNewLanguageTest.java

https://trello.com/c/XVe0QZtm/548-atmainnavigationmenusubmitnewlanguage-verify-link-textsvetlanag1011

 [AT][Main][navigation][menu][submitnewlanguage] Verify Link Text

---

src/test/java/pages/LPage.java
src/test/java/tests/CheckDownloadText.java
src/test/java/tests/LiliYnusovaTest.java

RF - https://trello.com/c/4OTdgU5l/549-rfstructurelpage-refactoring-lpage-pochekirya

[RF][Structure][LPage] Refactoring LPage <PocheKirya>

---

src/test/java/tests/ConflictResolvingPractice.java
src/test/java/tests/ConflictResolvingPracticeTest.java
src/test/java/tests/ShakespeareLanguageSiteTest.java

This is the new  class for practice

Initial commit to start practice

---

src/test/java/pages/StartPage.java
src/test/java/tests/AAA_MenuLyricsTest.java
src/test/java/tests/AAA_MenuStartLinksTest.java
src/test/java/tests/AAA_MenuTeamTest.java

https://trello.com/c/pmOWlVbX/522-tcstartmainlinks-verifylinkhistoricinformation-shurikgr

[AT][Start][main][links] VerifyLinkHistoricInformation <ShurikGr>

---

src/test/java/tests/ConflictResolvingPracticeTest.java

ConflictResolving

---

src/test/java/pages/SignV2Page.java

US - https://trello.com/c/SKbga6FH/562-ussignv2page-create-locator-for-test
AT - https://trello.com/c/dknaOIiy/566-atsignv2page-create-locator-for-testirenesnitko

[AT][Signv2Page] Create locator for test<IreneSnitko>

---

src/test/java/pages/JPage.java
src/test/java/tests/ServachakMariaVerifyJPageTest.java

US - https://trello.com/c/f1E8kB8W

[AT][J][main][table][th] created locator and methods on JPage, rename my class ServachakM

---

src/test/java/pages/DPage.java

https://trello.com/c/Ps1Kxj5J/567-usstructuredpage-create-dpage-create-webelement-create-methods

[US][Structure][DPage] Create DPage, create WebElement, create methods

---

src/test/java/pages/AbcPage.java
src/test/java/tests/KononirinIrinaShTest.java

https://trello.com/c/nZcoSaJg/558-rfabcpage-kononirin

[RF][ABCPage] Kononirin

---

src/test/java/tests/BrowseLanguagesZSubmenuTest.java

[AT][Z][main][table][tr] Verify numbers and names of all languages Z
https://trello.com/c/Js8lE5v1/530-atzmaintabletr-verify-numbers-and-names-of-all-languages-z
[US][Z][main][All]
https://trello.com/c/QrMVFvSG/336-uszmainall

[AT][Z][main][table][tr] Verify numbers and names of all languages Z

---

src/test/java/pages/SignV2Page.java

US - https://trello.com/c/hEMJHDH0/577-ussignv2page-create-method-for-test-a-captcha-image-display-verification
AT - https://trello.com/c/vEp18v95/582-atsignv2page-create-method-for-test-a-captcha-image-display-verificationirenesnitko

[AT][Signv2Page] Create method for test a captcha image display verification<IreneSnitko>

---

src/test/java/pages/TeamPage.java

US - https://trello.com/c/9oaMbQYz/594-usteammainh2-veryfi-text-h2-main-header
AT - https://trello.com/c/g8ysE8wJ/595-atteammainh2-veryfi-text-h2-main-header

[AT][team][main][h2] Veryfi Text H2 Main Header <NadiaLidt>

---

src/test/java/tests/IreneSnitkoTests.java

US - https://trello.com/c/9Bbil33v/568-ussignv2mainimage-captcha-checking-the-display-of-captchas-image
AT - https://trello.com/c/Vxh3fDxL/569-atsignv2mainimage-captcha-checking-the-display-of-captchas-imageirenesnitko

[AT][Signv2][main]image/captcha] Checking the display of captcha's image<IreneSnitko>

---

src/test/java/pages/GuestbookV2Page.java

[RF][Structure][GuestbookV2Page]addedNewLocatorMetod|As.A

---

src/test/java/tests/Song99BottlesAsTest.java

[AT][Submitnewlanguage]Verify link and text<Asel.A>

---

src/test/java/tests/IlyaCheshkovTest.java

https://trello.com/c/DXrnrAZU/606-atmainverify-h1-textilyuxaif
https://trello.com/c/dTGv1ZZX/603-usmainh1verifyheadertext

IlyaCheshkovTest class added, testVerifyH1Text test added

---

src/test/java/pages/SubmitNewLanguagePage.java

RF - https://trello.com/c/LNv3Rvte/608-rfsubmitnewlanguagemainheaderh3-submitnewlanguagepage-refactoring-method-gettitleh3text

[RF][Submitnewlanguage][main][header][h3] SubmitNewLanguagePage Refactoring method getTitleH3Text()

---

src/test/java/pages/UPage.java

https://trello.com/c/yFRjn8xM/616-usumainheaderh2-create-locator-and-methods

added locator and methods

---

src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/JSDGEWOL/614-atumainheaderh2-verify-text-viktoriiakarpus

ATUMainHeaderH2Verifytext

---

src/test/java/tests/VasiliySinTest.java

TC - https://trello.com/c/4mFUxrIG/605-tcsubmitnewlanguagemainheaderh3-verify-text-please-note
AT - https://trello.com/c/K5sZGmWX/607-atsubmitnewlanguagemainheaderh3-verify-text-please-note

[AT][Submitnewlanguage][main][header][h3] Verify text Please note:

---

src/test/java/pages/AbcPage.java
src/test/java/tests/Song99BoutleXbrookxTest.java

https://trello.com/c/XEXZO1WC/564-atdmainheaderh2-verify-h2-text-and-description-text-valentinkuprin

[AT][D][main][header][h2] Verify h2 text and description text

---

src/test/java/tests/IreneSnitkoTest.java

RF - https://trello.com/c/xOdJ7wNz/618-rfirenesnitkotests-refactoring-the-class-nameirenesnitko

[RF][IreneSnitkoTests] Refactoring the Class name<IreneSnitko>

---

src/test/java/pages/browse_languages/letters/JPage.java
src/test/java/tests/ServachakMariaVerifyJPageTest.java

US - https://trello.com/c/sgr2toiH

[AT][J][main][table][tr] Verify that all languages start with letter j ServachakM

---

src/test/java/tests/CheckCssOfInactiveStatusTest.java

RF - https://trello.com/c/Hkprqx3v/621-rfcheckcssofinactivestatus-refactoring-the-class-nameirenesnitko

[RF][CheckCssOfInactiveStatus] Refactoring the Class name<IreneSnitko>

---

src/test/java/tests/ServachakMariaVerifyJPageTest.java

US - https://trello.com/c/gmcd3pCN

[AT][J][main][table][tr] Check how many languages on JPage ServachakM

---

src/test/java/pages/browse_languages/languages/LanguageMathematicaPage.java
src/test/java/tests/AuthorOfMathematicaLanguageTest.java
src/test/java/tests/GalaKonTests.java

RF - https://trello.com/c/VI0OrjSo/602-rflanguagemathematicapagetdtablenadialidt

[RF][LanguageMathematicaPage][td][table]<NadiaLidt>

---

src/test/java/tests/CheckDownloadTextTest.java

RF - https://trello.com/c/kR6en6Hk/622-rfcheckdownloadtext-refactoring-the-class-name-irenesnitko

[RF][CheckDownloadText] Refactoring the Class name <IreneSnitko>

---

src/test/java/pages/browse_languages/letters/UPage.java

https://trello.com/c/Nh4EgYWl/626-atumaintextcreate-locator-and-methodsviktoriiakarpus

add locator and methods

---

src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/KFMV1YAR/624-atumaintextviktoriiakarpus

testUSubmenuDescription

---

src/test/java/tests/CountCommentOfLanguageShakespeareTest.java

RF - https://trello.com/c/ZeV6PTgf/630-rfcountcommentoflanguageshakespeare-refactoring-the-class-nameirenesnitko

[RF][CountCommentOfLanguageShakespeare] Refactoring the Class name<IreneSnitko>

---

src/test/java/tests/MorigorHWTest.java

RF - https://trello.com/c/RBzMezwe/631-rfmorigorhwtests-refactoring-the-class-nameirenesnitko

[RF][MorigorHWTests] Refactoring the Class name<IreneSnitko>

---

src/test/java/tests/BrowseLanguagesZSubmenuTest.java

https://trello.com/c/eslPm4Gc/632-rfzpage-fix-bugs-in-methods
[RF][Z][main][all]Added one method in class
https://trello.com/c/QrMVFvSG/336-uszmainall
[US][Z][main][All]

[RF][Z][main][all]Added one method in class

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/browse_languages/letters/IPage.java

https://trello.com/c/tK1vAzRb/643-atstructureipagecreate-ipage-methods-locators-driver-ilyuxaif
https://trello.com/c/vofNROVk/641-usstructureipagecreate-ipage-methods-locators-driver

Created [AT][Structure][IPage]Create IPage Methods, Locators, Driver <ilyuxaif>

---

src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/9QB2L63O/644-rfrename-all-testsnameviktoriiakarpus

Rename all tests'name

---

src/test/java/tests/SharingLanguageByRedditTest.java

RF - https://trello.com/c/ceNAO6XZ/633-rfsharinglanguagebyreddit-refactoring-the-class-nameirenesnitko

[RF][SharingLanguageByReddit] Refactoring the Class name<IreneSnitko>

---

src/test/java/tests/СompareRealLinksSearchLanguagesTest.java

RF - https://trello.com/c/T3gqasJP/645-rf%D1%81omparereallinkssearchlanguages-refactoring-the-class-nameirenesnitko

[RF][СompareRealLinksSearchLanguages] Refactoring the Class name<IreneSnitko>

---

src/test/java/pages/start/TeamPage.java

https://trello.com/c/ntbHlSIx/647-atpage-nametask-namegithub-nickname
https://trello.com/c/Vt507WwL/646-usstructureteam-created-locator-links

[AT][TeamPage][main][link] Checking link Created Locator Oliver Schade

---

src/test/java/tests/TatianaPTest.java

https://trello.com/c/y8GZTboJ/640-atsearchmainformverify-submitsearch-is-cliackabledmswlpk
https://trello.com/c/2a05lFHr/639-ussearchmainformverify-submitsearch-is-cliackabledmswlpk

[AT][Search][main][form]Verify SubmitSearch is Cliackable<dmswlpk>

---

src/test/java/pages/browse_languages/letters/SPage.java
src/test/java/tests/CountCommentOfLanguageShakespeareTest.java
src/test/java/tests/ShakespeareLanguageSiteTest.java

https://trello.com/c/8DtKsPqI/658-rfstructurespage-refactoring-spage-morigor

[RF][Structure][SPage] Refactoring SPage <Morigor>

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/browse_languages/letters/YPage.java

US  https://trello.com/c/rf2y4aj9/670-usstructureypage-create-ypage-with-methods-locator-driver
AT  https://trello.com/c/gIOasRVX/671-atstructureypage-create-ypage-with-methods-locator-driver-morigor

[AT][Structure][YPage] Create YPage with Methods, Locator, Driver <Morigor>

---

src/test/java/pages/browse_languages/letters/ZeroPage.java

https://trello.com/c/ypXeGMTT/675-atstructurezeropage-create-zeropage-sabinasaad
https://trello.com/c/4QdWvoqp/674-usstructurezeropage-create-zeropage-sabinasaad

[AT][Structure][ZeroPage] Create ZeroPage <sabinasaad>

---

src/test/java/tests/ViktroriiaKTest.java

https://trello.com/c/dmyCsqSw/680-atupageverify-table-header-language-author-date-comments-rateviktoriiakarpus

Verify Table Header

---

src/test/java/pages/browse_languages/languages/LanguagesBeginWithZ.java

https://trello.com/c/IbtZgn5n/683-usstructurelanguagesbeginwithz-create-locators-and-methods
[US][Structure][LanguagesBeginWithZ] Create locators and methods
https://trello.com/c/cUPA7d6Y/685-atstructurelanguagesbeginwithz-create-locators-and-methods
[AT][Structure][LanguagesBeginWithZ] Create locators and methods
Создала общую страницу для всех языков, которые начинаются на букву "Зи".

[AT][Structure][LanguagesBeginWithZ] Create locators and methods

---

src/test/java/pages/browse_languages/letters/JPage.java
src/test/java/tests/ServachakMariaVerifyJPageTest.java

US- https://trello.com/c/yINxL0x0

[AT][J][main][table][tr] Verify random Tr is displayed, is enabled and not empty ServachakM

---

src/test/java/pages/browse_languages/AbcPage.java

US  https://trello.com/c/ClAt7jt6/689-usstructureabcpage-create-methods-and-locator
AT  https://trello.com/c/5IHpcvnb/690-atstructureabcpage-create-methods-and-locator-morigor

[AT][Structure][AbcPage] Create Methods and Locator <Morigor>

---

src/test/java/tests/TopListTest.java

https://trello.com/c/r5u5vgU3/225-attoplistsubmenunewcomments-verify-text-ksutitova
https://trello.com/c/j6pOv2ts/224-ustoplistsubmenunewcomments-verify-text-ksutitova

[AT][Toplist][submenu][newcomments] Verify Text <ksutitova>

---

src/test/java/pages/browse_languages/letters/IPage.java
src/test/java/tests/IlyaCheshkovTest.java

https://trello.com/c/G7CRFhhg/699-atimaintabletr-check-languages-count-on-ipage

[AT][I][MAIN][TABLE][TR] Check languages count on IPage <ilyuxaif>

---

src/test/java/pages/start/TeamPage.java

https://trello.com/c/ONapXp7e/700-atteammainlink-created-locators-all-links-olga-saf
https://trello.com/c/Vt507WwL/646-usstructureteam-created-locator-links

[AT][Team][main][link] Created Locators All links <>

---

src/test/java/pages/browse_languages/letters/XPage.java

US  https://trello.com/c/qLYx5kNy/697-usstructurexpage-create-xpage-with-methods-locator-driver
AT  https://trello.com/c/RQvimYf1/698-atstructurexpage-create-xpage-with-methods-locator-driver-morigor

[AT][Structure][XPage] Create XPage with Methods, Locator, Driver <Morigor>

---

src/test/java/tests/SubmitNewLanguageTest.java

https://trello.com/c/wSaZ5dSK/512-atmainnavigationmenusubmitnewlanguage-verify-navigation-svetlanag1011

[AT][Main][navigation][menu][submitnewlanguage] Verify Navigation

---

src/test/java/tests/OlgaSafMenuStartPageTest.java

https://trello.com/c/VbSSjTTi/701-atteammainlink-check-all-links-on-click-olga-saf
https://trello.com/c/Vt507WwL/646-usstructureteam-created-locator-links

[AT][Team][main][link] Check All Links On Click

---

src/test/java/tests/OlgaSafMenuStartPageTest.java

https://trello.com/c/kS0ruhQc/716-rfteammainlink-check-all-links-on-click-testolga-saf
https://trello.com/c/VbSSjTTi/701-atteammainlink-check-all-links-on-click-olga-saf

[RF][Team][main][link] Check All Links On Click Test

---

src/test/java/tests/MorigorProjectAllTest.java

created testVerifyNumberOfXLanguages()
US  https://trello.com/c/7Qd8Q2Q8/702-usxmaintabletr-verify-number-of-languages-on-xpage
AT  https://trello.com/c/Z1ofUS2U/704-atxmaintabletr-verify-number-of-languages-on-xpage-morigor

[AT][X][main][table][tr] Verify number of languages on XPage <Morigor>

---

src/test/java/pages/guestbook/SignV2Page.java

change method's name from 'getInputComment' to 'setInputComment'. for page: "SignV2Page"

change method's name from 'getInputComment' to 'setInputComment'.

---

src/test/java/pages/browse_languages/letters/CPage.java

[US] -https://trello.com/c/ajHXm2dT/719-usstructurecpage-create-locator-and-methods-for-the-test-annaabg
[AT] -https://trello.com/c/RXHaIyx2/720-atstructurecpage-create-locator-and-methods-for-the-test-annaabg

[AT][CPage] Create locator and methods for the test <AnnaAbg>

---

src/test/java/pages/MainPage.java

[AT][Main][Footer] lokators and methods added<AnaLama>

[AT][Main][Footer][search] Search Languages Button Test <AnaLama>

---

src/test/java/pages/MainPage.java
src/test/java/tests/AnaLamaFooterMenuBarButtonsTest.java

Footer search button test added
https://trello.com/c/tkdEhteU/241-atmainfootersearch-search-languages-button-test-analama

[AT][Main][Footer][search] SearchButton Test <AnaLama>

---

src/test/java/tests/GuestbookSignInputFormTest.java

US_600.013 | Guestbook | Sign guestbook | Check all input fields

create test with guestbook input fields

---

src/test/java/pages/browse_languages/letters/RPage.java

https://trello.com/c/Ht8zq0Kp/712-atstructurermaintableth-add-locator-thtags-add-methods-getthtags-getthtagstextsvetlanag1011

[AT][Structure][R][main][table][th] Add locator TH_TAGS, add methods

---

src/test/java/pages/start/StartPage.java

AT - https://trello.com/c/8YGtM0n3/731-atstructurestartpagecreate-locator-h2-header-and-methods
US - https://trello.com/c/h6ZAFN6u/730-usstructurestartpagecreate-locator-h2-header-and-methods

[AT][Structure][StartPage]Create locator H2 Header and methods

---

src/test/java/pages/browse_languages/languages/LanguagesBeginWithZ.java

https://trello.com/c/dqMXteD6/725-rfstructurelanguagesbeginwithz08alimduil
[RF][Structure][LanguagesBeginWithZ]Added more locators and methods 
https://trello.com/c/IbtZgn5n/683-usstructurelanguagesbeginwithz-create-locators-and-methods
[US][Structure][LanguagesBeginWithZ] Create locators and methods

[RF][Structure][LanguagesBeginWithZ]Added more locators and methods 

---

src/test/java/pages/guestbook/SignV2Page.java

https://trello.com/c/XFsH7cT2/355-at600013-guestbook-sign-guestbook-check-all-input-fields

My method's namechange

---

src/test/java/pages/browse_languages/letters/JPage.java

RF - https://trello.com/c/Mt7VvY38/723-rfjpagerefactoring-methods-modifier-and-code-reformatirenesnitko

[RF][JPage]Refactoring method's modifier and code reformat<IreneSnitko>

---

src/test/java/pages/browse_languages/languages/LanguageCSharp1614Page.java

[US] - https://trello.com/c/TqaBm1FA/728-usstructurelanguagecsharp1614page-create-locator-and-methods-annaabg
[AT] - https://trello.com/c/LoGvQOSk/729-atstructurelanguagecsharp1614page-create-locator-and-methods-annaabg

[AT][Structure][LanguageCSharp1614Page] Create locator and methods <AnnaAbg>

---

src/test/java/tests/BrowseLanguagesAllBeginWithZ.java
src/test/java/tests/BrowseLanguagesAllBeginWithZTest.java

https://trello.com/c/KPDpLwP0/733-atanylanguagebeginwithzmaintext08alimduil
[AT][AnyLanguageBeginWithZ][main][text]
https://trello.com/c/AtOSSRzg/727-usanylanguagebeginwithzmaintext
[US][AnyLanguageBeginWithZ][All]

[AT][AnyLanguageBeginWithZ][main][text]

---

src/test/java/tests/CountCSharpLanguageVersionsTest.java

[US] -https://trello.com/c/vQU6R52U/734-uslanguagecsharp1614pagemaintabletr-count-c-language-versions-annaabg
[AT] - https://trello.com/c/dXNYhvj3/736-atlanguagecsharp1614pagemaintabletr-count-c-language-versions-annaabg
[TC] - https://trello.com/c/wJkKawbd/738-tclanguagecsharp1614pagemaintabletr-count-c-language-versions-annaabg

[AT][LanguageCSharp1614Page][main][table][tr] Count C# Language Versions <AnnaAbg>

---

src/test/java/tests/SvetlanaGTest.java

https://trello.com/c/nIskfDAZ/710-atrmaintableth-verify-table-headersvetlanag1011

[AT][R][main][table][th] Verify table headers

---

src/test/java/pages/browse_languages/letters/IPage.java
src/test/java/tests/IlyaCheshkovTest.java

https://trello.com/c/iS3CUygr/737-atstructureipage-check-all-table-links-clickable-and-exist-ilyuxaif
https://trello.com/c/TEPvROEs/735-usstructureipage-check-all-table-links-clickable-and-exist

Finally finished [AT][Structure][IPage] Check All Table Links Clickable And Exist Tests

---

src/test/java/pages/MainPage.java

https://trello.com/c/NiHkvSOz/749-atmainonload-add-locator-onloadsettings-and-method-getonloadsettings

[AT][Main][onload] Add locator ONLOAD_SETTINGS and method get

---

src/test/java/tests/TopListTest.java

https://trello.com/c/DL8PIvSI/751-attoplistrealmaintabletr-count-the-number-of-languages-ksutitova
https://trello.com/c/VInn048j/750-ustoplistrealmaintabletrcount-the-number-of-languages-ksutitova

[AT][TopList][main][table][tr] Count the number of languages <ksutitova>

---

src/test/java/pages/browse_languages/languages/AlphaBetaPage.java

…[AT][Structure][[AlphaBetaPage]Create AlphaBeta Page added new locators and metods<Asel.A>
https://trello.com/c/OUnUxp8X

[AT][Structure][[AlphaBetaPage]CreateAlphaBetaPage <Asel.A>

---

src/test/java/tests/SvetlanaGTest.java

https://trello.com/c/U17ZYACp/747-atmainonload-verify-onload-settingssvetlanag1011

[AT][Main][onload] Verify onload settings

---

src/test/java/pages/top_lists/TopListPage.java
src/test/java/tests/TopListTest.java

https://trello.com/c/IA3fev7k/754-attoplistmaintablelink-create-metod-ksutitova
https://trello.com/c/ljthkmkf/753-ustoplistmaintablelink-create-metod-ksutitova

[AT][Toplist][main][table][link] create metod <ksutitova>

---

src/test/java/pages/BasePage.java
src/test/java/pages/MainPage.java
src/test/java/pages/start/LyricsPage.java
src/test/java/pages/start/StartPage.java
src/test/java/runner/BaseTest.java
src/test/java/runner/TestUtils.java
src/test/java/tests/LessonsTest.java
src/test/java/tests/Song99BottlesKononirinIrinaShTest.java

BasePage and TestUtils created, 
POM model changed, 
LessonsTest and Song99BottlesKononirinIrinaShTest changed using new POM
https://trello.com/c/9ISTuULo/756-rfstructurepom-refactoring

[RF][Structure]POM refactoring

---

src/test/java/pages/BasePage.java
src/test/java/pages/MainPage.java
src/test/java/pages/guestbook/GuestbookV2Page.java
src/test/java/pages/guestbook/SignV2Page.java
src/test/java/runner/TestUtils.java
src/test/java/tests/MaksPtTest.java

Refactoring SignV2Page and MaksTest
Added new methods in TestUtils, MainPage, BasePage
https://trello.com/c/Cfu48zs6/757-rfstructuresignv2pagemakspt

[RF][Structure][SignV2Page]<MaksPt>

---

src/test/java/pages/start/StartPage.java
src/test/java/pages/start/TeamPage.java
src/test/java/tests/HelenVelTest.java
src/test/java/tests/TeamTest.java

Refactoring TeamPage, StartPage and TeamTest
https://trello.com/c/GqT7wFZt/759-rfstructureteampagerom-t

[RF][Structure][TeamPage]<Rom-T>

---

src/test/java/pages/guestbook/GuestbookV2Page.java

Refactoring GuestbookV2Page
https://trello.com/c/TcVWniap/760-rfstructureguestbookv2pagemakspt

[RF][Structure][GuestbookV2Page]<MaksPt>

---

src/test/java/pages/MainPage.java
src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/guestbook/SignV2Page.java
src/test/java/tests/MorigorProjectAllTest.java

https://trello.com/c/zxOYwgbp/769-rfstructuremainpageypagemorigor

[RF][Structure][MainPage][AbcPage][SignV2Page]<Morigor>

---

src/test/java/pages/start/TeamPage.java
src/test/java/tests/GalaKonTest.java

[RF] https://trello.com/c/js7ElIFd/766-rfstartteampageverify-websites-linksgalakon
1.
public TeamPage clickOliverSchadeLink()
2. 
public TeamPage clickGregorScheithauerLink()
3.
public static String getTeamPageWebsitesLinksTitles()

[RF][Start][TeamPage]Verify website's links

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/browse_languages/languages/LanguageJava3Page.java
src/test/java/pages/browse_languages/letters/JPage.java
src/test/java/tests/BrowseLanguageJavaTest.java

Refactoring AbcPage, JPage, LanguageJava3Page and BrowseLanguageJavaTest
https://trello.com/c/6ZDI2Aw9/762-rfstructurelanguagejava3pagerom-t

[RF][Structure][LanguageJava3Page]<Rom-T>

---

src/test/java/pages/MainPage.java
src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/search_languages/SearchPage.java
src/test/java/pages/start/InfoPage.java
src/test/java/pages/start/StartPage.java
src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
src/test/java/tests/NadiaLidtTest.java

RF - https://trello.com/c/DxQW7dIx/767-rfstructurepom-refactoringnadialidt

[RF][Structure]POM refactoring<NadiaLidt>

---

src/test/java/pages/start/InfoPage.java
src/test/java/runner/TestUtils.java
src/test/java/tests/_to_do/IreneSnitkoTest.java
src/test/java/tests/start/InfoTest.java

RF - https://trello.com/c/7JkChQ6u/768-rfstructurestartpageinfopagetestutilsirenesnitkotestrefactoring-testclass-and-pagesirenesnitko

[RF][Structure][StartPage][InfoPage][TestUtils][InfoTest]RefactoringTestCodeOfBasicOnInfoPage and POM<IreneSnitko>

---

src/test/java/pages/top_lists/TopListPage.java
src/test/java/pages/top_lists/TopListTopHitsPage.java
src/test/java/tests/browse_languages/languages/LanguageShakespeareTest.java

class LanguageShakespeareTest created, testAndCompareShakespeareLanguageLinkFromTwoPages() added
US  https://trello.com/c/VdFdGNo7/739-uslanguageshakespeare664maintablelink-compare-similar-link-to-languageshakespearepage-on-spage-and-on-toplisttophitspage
AT  https://trello.com/c/ngcEH3mM/741-atlanguageshakespeare664maintablelink-compare-similar-link-to-languageshakespearepage-on-spage-and-on-toplisttophitspage-morigor

[AT][LanguageShakespeare664][main][table][link] Compare similar link to LanguageShakespearePage on SPage and on TopListTopHitsPage <Morigor>

---

src/test/java/tests/_to_do/SvetlanaGTest.java
src/test/java/tests/main/MainTest.java

https://trello.com/c/beU1OxWb/773-rfmainonload-moving-test-and-refactoring-test-in-new-pom-svetlanag1011

[RF][Main][onload] Moving testVerifyOnloadSettings  and refactoring test in new POM

---

src/test/java/pages/BasePage.java
src/test/java/pages/browse_languages/letters/APage.java
src/test/java/pages/browse_languages/letters/CPage.java
src/test/java/pages/browse_languages/letters/DPage.java
src/test/java/pages/browse_languages/letters/IPage.java
src/test/java/pages/browse_languages/letters/JPage.java
src/test/java/pages/browse_languages/letters/_LettersPage.java
src/test/java/tests/_to_do/GalaKonTest.java
src/test/java/tests/_to_do/IlyaCheshkovTest.java
src/test/java/tests/_to_do/IreneSnitkoTest.java
src/test/java/tests/_to_do/OlgaSafMenuStartPageTest.java
src/test/java/tests/_to_do/ServachakMariaVerifyJPageTest.java
src/test/java/tests/_to_do/Song99BoutleXbrookxTest.java

Page created LettersPage
Pages used in the Refactoring
APage
CPage
DPage
IPage
JPage

[RF][Structure][LettersPage]

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/browse_languages/languages/LanguageCSharp1614Page.java
src/test/java/pages/browse_languages/languages/LanguagePerl737Page.java
src/test/java/pages/browse_languages/languages/LanguagePython808Page.java
src/test/java/pages/browse_languages/letters/CPage.java
src/test/java/pages/browse_languages/letters/PPage.java
src/test/java/pages/search_languages/SearchPage.java
src/test/java/tests/_to_do/CountCSharpLanguageVersionsTest.java
src/test/java/tests/_to_do/VerifyPerlLanguageFeaturesTest.java
src/test/java/tests/_to_do/VerifyPythonInfoLinkTest.java

[RF] -https://trello.com/c/NLz0IC73/770-rfstructureabcpagesearchpagecpageppagelanguagecsharp1614pagelanguageperl737pagelanguagepython808page-refactoring-pages-and-tests

[RF][Structure] Refactoring Pages and Tests <AnnaAbg>

---

src/test/java/tests/start/InfoTest.java

RF https://trello.com/c/nj83X2lR/777-rfstructuretask-namegithub-nick

[RF][InfoPage]Moving Test to Info Test<dmswlpk>

---

src/test/java/pages/top_lists/NewCommentsPage.java
src/test/java/pages/top_lists/TopListPage.java
src/test/java/tests/_to_do/TatianaPTest.java
src/test/java/tests/_to_do/TopListTest.java
src/test/java/tests/top_lists/NewCommentsTest.java

https://trello.com/c/D4uiWMSA/778-rfnewcommentspagemoving-testsdmswlpk

[RF][NewCommentsPage]Moving Tests<dmswlpk>

---

src/test/java/pages/start/TeamPage.java
src/test/java/tests/start/TeamTest.java

[RF] https://trello.com/c/vKZbVKtU/781-rfstartteampageverify-websites-links-according-new-pomgalakon
The method is refactored: two different ones are created for verifying two different links. The test is refactored: two different ones are created for verifying two different links.

[RF][Start][TeamPage]Verify website's links according new POM

---

src/test/java/pages/start/TeamPage.java

US https://trello.com/c/KwJEf3fQ/784-usstartteampageverify-stefan-scheler-websites-linkgalakon
TC https://trello.com/c/CE39vpE0/787-tcstartteampagecreate-locator-and-method-to-verify-stefan-scheler-websites-linkgalakon 
Methods created for the test: WebElement getStefanSchelerLink, TeamPage clickStefanSchelerLink, String getTeamPageStsSynfloodDeLinkTitle

[Start][TeamPage]Verify Stefan Scheler website's link

---

src/test/java/pages/guestbook/SignV2Page.java
src/test/java/runner/TestUtils.java
src/test/java/tests/_to_do/IreneSnitkoTest.java
src/test/java/tests/guestbook/SignV2Test.java

RF - https://trello.com/c/iC7wmaFH/782-rfsignv2pagetestutilsrefactoring-testattributessrcofmessageicons-and-pagesirenesnitko

[RF][SignV2Page][TestUtils]Refactoring testAttributesSrcOfMessageIcons and pages<IreneSnitko>

---

src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java

RF - https://trello.com/c/kT0Uira8/798-rfsubmitnewlanguagetesttesterrormessagesubmitlanguagebuttonnadialidt

[RF][SubmitNewLanguageTest][testErrorMessageSubmitLanguageButton]refactoring test<NadiaLidt>

---

src/test/java/pages/browse_languages/letters/JPage.java
src/test/java/pages/browse_languages/letters/_LettersPage.java
src/test/java/tests/_to_do/IreneSnitkoTest.java

https://trello.com/c/tS94AAE2/806-rfstructureletterspagejpaje
Pages used in the Refactoring:
LettersPage
JPaje
Methods changed for the test:
clickLanguageJavascript1948() - deleted from JPaje
clickLanguageFromTDLinks(String nameLanguage) - added to LettersPage

[RF][Structure][LettersPage][JPaje]

---

src/test/java/pages/browse_languages/languages/LanguageJava3Page.java

Changed the access modifier of the getAllVersionsNameAndComment()  from public to private 
https://trello.com/c/BwitGyFV/807-rflanguagejava3pagerom-t

[RF][LanguageJava3Page] Change access modifier for method<Rom-T>

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/browse_languages/letters/IPage.java
src/test/java/tests/_to_do/IlyaCheshkovTest.java
src/test/java/tests/browse_languages/letters/ITest.java

RF - https://trello.com/c/Cebs404j/810-rfstructureipage-refactoring-ipage-ilyuxaif

[RF][Structure][IPage] Refactoring IPage <ilyuxaif>

---

src/test/java/pages/start/StartPage.java
src/test/java/tests/_to_do/OlgaSafMenuStartPageTest.java
src/test/java/tests/start/StartTest.java

https://trello.com/c/gW1uZtga/812-rfstructurestartpagerefactoring-starttestolgasaf

[RF][Structure][StartPage]Refactoring StartTest<OlgaSaf>

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/tests/_to_do/BrowseLanguagesZSubmenuTest.java
src/test/java/tests/browse_languages/letters/ZTest.java

https://trello.com/c/EfcFyX1m/791-rfabcpagepage-refactoring-new-pom08alimduil
[RF][AbcPage]Page refactoring new POM<08AlimDuiL>
https://trello.com/c/eQAY8YEk/811-atzmain-added-tests-from-old-class
[AT][Z][main] Added tests from old class
Создала класс ZTest. В него перенесла переделанные по новой структуре тесты из класса BrowseLanguagesZSubmenuTest. На странице [AbcPage] переделала один метод, чтобы можно было возвращать страницу ZPage.

Added ZTest refactored BrowseLanguagesZSubmenuTest Abc page

---

src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
src/test/java/tests/_to_do/IreneSnitkoTest.java
src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java

RF - https://trello.com/c/JcEx9jDj/819-rfsubmitnewlanguagetestsubmitnewlanguagepageirenesnitkotestrefactoring-testattributesrccaptcha-and-delete-testclassirenesnitko

Rf/submit new language test/test attribute src captcha/irene snitko

---

src/test/java/tests/browse_languages/letters/UTest.java

https://trello.com/c/s7HMDbuV/822-rfutestrefactoring-testviktoriiakarpus

RFUTestRefactoringTestViktoriiaKarpus

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/xELvia1a/817-atmainnavigationmenuabc-verify-text

[AT][Main][navigation][menu][abc] Verify Text

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/4UUfg9p7/816-atmainnavigationmenuabc-verify-link-text

[AT][Main][navigation][menu][abc] Verify Link Text

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/Oz7yBSw4/805-atmainnavigationmenustart-verify-navigation

[AT][Main][navigation][menu][abc] Verify Navigation

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/tests/browse_languages/letters/UTest.java

https://trello.com/c/vgTFEjCP/824-rfutestrefactoring-testtestcountlanguagesu-viktoriiakarpus

RFUTestRefactoringTestTestCountLanguagesUViktoriiaKarpus

---

src/test/java/pages/guestbook/SignV2Page.java
src/test/java/tests/guestbook/SignV2Test.java

https://trello.com/c/T5vJsng3/828-rfstructuresignv2pagesignv2test
Pages used in the Refactoring
SignV2Test
SignV2Page
Methods changed
fillAllFields()
clickButtonSubmit()
testEmptyFormError()
testErrorTextFont()
testErrorTextBackgroundColor()

[RF][Structure][SignV2Page][SignV2Test]

---

src/test/java/tests/_to_do/OlgaSafMenuStartPageTest.java
src/test/java/tests/start/TeamTest.java

RF -  https://trello.com/c/MtUy61tc/830-rfstructurerefactoring-testclass-olgasafmenustartpagetest-olgasaf

[RF][Structure]Refactoring TestClass OlgaSafMenuStartPageTest

---

src/test/java/tests/_to_do/OlgaSafMenuStartPageTest.java
src/test/java/tests/browse_languages/letters/ATest.java

RF -  https://trello.com/c/14iMI57n/831-rfstructureapagerefactoring-tests-created-atestolgasaf

[RF][Structure][APage]Created ATest <OlgaSaf>

---

src/test/java/tests/_to_do/OlgaSafMenuStartPageTest.java
src/test/java/tests/browse_languages/letters/ATest.java
src/test/java/tests/browse_languages/letters/CTest.java

RF  -  https://trello.com/c/nZNOEug6/833-rfstructurecpagecreated-ctest-olgasaf

[RF][Structure][CPage]Created CTest and Cleaned ATest

---

src/test/java/tests/browse_languages/letters/UTest.java

https://trello.com/c/Fqem61eo/826-rfutestrefactoring-testtesttitleupageviktoriiakarpus

RefactoringTestTittleUPage

---

src/test/java/pages/top_lists/TopListPage.java
src/test/java/tests/_to_do/TopListTest.java
src/test/java/tests/top_lists/ToplistEsotericTest.java

https://trello.com/c/BqynzQgR/827-rftoplistesoterictestksutitova

ToplistEsotericTest added class

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/tests/_to_do/IlyaCheshkovTest.java
src/test/java/tests/browse_languages/letters/ITest.java

https://trello.com/c/u6OUzBjP/836-rfstructureipage-refactoring-ipage-adding-tests-ilyuxaif

Refactored ITest tests, deleted old tests

---

src/test/java/pages/browse_languages/AbcPage.java
src/test/java/pages/browse_languages/languages/LanguageMathematicaPage.java
src/test/java/pages/browse_languages/letters/MPage.java
src/test/java/tests/_to_do/HelenVelTest.java
src/test/java/tests/_to_do/MorigorHWTest.java
src/test/java/tests/browse_languages/languages/LanguageMathematicaTest.java
src/test/java/tests/browse_languages/letters/MTest.java

https://trello.com/c/vfxrbqQ8/823-rfmoving-and-refactoring-tests-in-morigorhwtest-class-morigor

[RF][Moving and Refactoring tests in MorigorHWTest class <Morigor>

---

src/test/java/pages/BasePage.java
src/test/java/tests/_to_do/IreneSnitkoTest.java
src/test/java/tests/browse_languages/languages/LanguageJavascript1948Test.java

RF - https://trello.com/c/uXW4M63W/832-rflanguagejavascript1948testbasepagerefactoring-testlinktowikipedia-and-add-methodirenesnitko

[RF][LanguageJavascript1948Test][BasePage]Refactoring testLinkToWikipedia add TestClass and method<IreneSnitko>

---

src/test/java/tests/_to_do/TopListTest.java
src/test/java/tests/top_lists/TophitsTest.java

https://trello.com/c/LUck7ZFB/840-rftophitstestksutitova

refactor for POM TophitsTest

---

src/test/java/tests/_to_do/MorigorHWTest.java

https://trello.com/c/bNZFFIHn/839-rf-refactoring-class-morigorhwtest-morigor

[RF][] refactoring class MorigorHWTest <Morigor>

---

src/test/java/pages/top_lists/TopListPage.java
src/test/java/tests/_to_do/TopListTest.java
src/test/java/tests/top_lists/TopListNewLanguagesThisMonthTest.java

https://trello.com/c/FjU0CLfD/844-rftoplistnewlanguagesthismonthtestksutitova

added new class for POM TopListNewLanguagesThisMonthTest

---

src/test/java/tests/browse_languages/letters/ITest.java

https://trello.com/c/kiLYYp7O/848-rfitest-refactoring-testcheckalltablelinksclickable-test-ilyuxaif

Refactored testCheckAllTableLinksClickable Test

---

src/test/java/pages/guestbook/SignV2Page.java
src/test/java/runner/TestUtils.java

RF - https://trello.com/c/zpc8jZPH/847-rfsignv2pagetestutilsrefactoring-methods-for-testirenesnitko

[RF][SignV2Page][TestUtils]Refactoring methods for test<IreneSnitko>

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/n1LKEx4H/849-atmainnavigationmenusearch-verify-text

[AT][Main][navigation][menu][search] Verify Text

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/GYTTuKVD/850-atmainnavigationmenusearch-verify-link-text

[AT][Main][navigation][menu][search] Verify Link Text

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/QAuMkpEv/851-atmainnavigationmenusearch-verify-navigation

[AT][Main][navigation][menu][search] Verify Navigation

---

src/test/java/tests/guestbook/SignV2Test.java

[AT[Guestbook][Sign guestbook] Max simbols for login is 100 <karinka83>](https://trello.com/c/FCdpJFOl/360-atguestbooksign-guestbook-max-simbols-for-login-is-100-karinka83)

added test for Guestbook page with randomly max symbols

---

src/test/java/tests/guestbook/SignV2Test.java

US - https://trello.com/c/UAlcsmf3/859-ussignv2mainpromptstest-text-from-promptsirenesnitko
AT - https://trello.com/c/x895EQOq/860-atsignv2mainpromptstest-text-from-promptsirenesnitko

[AT][SignV2][main][prompts]Test text from prompts<IreneSnitko>

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/FGXunlPr/853-atmainnavigationmenutoplist-verify-text

[AT][Main][navigation][menu][toplist] Verify Text

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/WOE8UIko/855-atmainnavigationmenutoplist-verify-navigation

[AT][Main][navigation][menu][toplist] Verify Navigation

---

src/test/java/tests/main/NavigationTest.java

US - https://trello.com/c/mMZe29RK/865-usmainnavigationmenuguestbookv2-verify-text-link-text-navigation
AT - https://trello.com/c/xVViRmuy/867-atmainnavigationmenuguestbookv2-verify-text-link-text-navigation-nadialidt

[AT][Main][navigation][menu][GuestbookV2] Verify Text <NadiaLidt>

---

src/test/java/tests/main/NavigationTest.java

UT - https://trello.com/c/mMZe29RK/865-usmainnavigationmenuguestbookv2-verify-text-link-text-navigation
AT - https://trello.com/c/SAIbsCkD/868-atmainnavigationmenuguestbookv2-link-text-nadialidt

[AT][Main][navigation][menu][GuestbookV2] Link text <NadiaLidt>

---

src/test/java/pages/browse_languages/languages/LanguageCSharp1614Page.java
src/test/java/pages/browse_languages/languages/_LanguagesPage.java
src/test/java/tests/browse_languages/languages/LanguageCSharpTest.java

[RF] -https://trello.com/c/2bYaoGpj/870-rflanguagecsharp1614page-page-test-refactoring-annaabg?filter=member:abgariananna8

[RF][LanguageCSharp1614Page] Page / Test Refactoring

---

src/test/java/tests/main/NavigationTest.java

US - https://trello.com/c/mMZe29RK/865-usmainnavigationmenuguestbookv2-verify-text-link-text-navigation
AT - https://trello.com/c/ZlrdCUjL/869-atmainnavigationmenuguestbookv2-navigation-nadialidt

[AT][Main][navigation][menu][GuestbookV2] Navigation <NadiaLidt>

---

src/test/java/tests/main/NavigationTest.java

https://trello.com/c/L5qznRvs/852-rfmainnavigationmenuabc-verify-navigation

[RF][Main][navigation][menu][start] Verify Navigation

---

src/test/java/tests/top_lists/ToplistAssemblyTest.java

US   https://trello.com/c/wgEgfcKl/875-ustoplistsubmenutoplistassemblytr-count-number-of-languages-morigor
AT   https://trello.com/c/ZQq4j2tO/876-attoplistsubmenutoplistassemblytr-count-number-of-languages-morigor

[AT][Toplist][submenu][toplist_assembly][Tr] Count number of languages <Morigor>

---

src/test/java/pages/guestbook/SignV2Page.java

US - https://trello.com/c/PlHQuB9D/874-ussignv2pageadd-methods-for-test-display-captcha
AT - https://trello.com/c/o2W1z7IH/883-atsignv2pageadd-methods-for-test-display-captchairenesnitko

[AT][Signv2Page]Add methods for test display captcha<IreneSnitko>

---

src/test/java/tests/guestbook/SignV2Test.java

US - https://trello.com/c/kcrhyh3D/873-ussignv2mainimage-captchatest-the-display-of-captcha
RF - https://trello.com/c/Hu4qipbv/885-rfsignv2mainimagecaptcha-refactoring-testthedisplayofcaptchairenesnitko

[RF][Signv2][main][imageCaptcha] Refactoring testTheDisplayOfCaptcha<IreneSnitko>

---

src/test/java/pages/browse_languages/BaseAbcPage.java
src/test/java/pages/browse_languages/letters/BPage.java

US  https://trello.com/c/wys4scsy/877-usstructurebpage-create-bpage-and-add-new-locators-and-methods
AT  https://trello.com/c/Opi7N5uE/878-atstructurebpage-create-bpage-and-add-new-locators-and-methods-morigor

[AT][Structure][BPage] Create BPage and add new locators and methods <Morigor>

---

src/test/java/pages/browse_languages/BaseAbcPage.java
src/test/java/pages/browse_languages/letters/BPage.java
src/test/java/tests/browse_languages/letters/BTest.java

US  https://trello.com/c/nwnTuPCo/888-usbmaintabletr-verify-number-of-languages-on-bpage
AT  https://trello.com/c/u5HOA1oL/889-atbmaintabletr-verify-number-of-languages-on-bpage-morigor

[AT][B][main][table][tr] Verify number of languages on BPage <Morigor>

---

src/test/java/tests/search_languages/SearchLanguagesTest.java

US https://trello.com/c/QjLVkPhk/891-ussearchmainform-verify-that-search-1c-enterprize-is-returning-1-result
AT https://trello.com/c/6aydw0c5/892-atsearchmainform-verify-that-search-1c-enterprize-is-returning-1-result-rom-t

[AT][Search][main][form] Verify that search "1C Enterprize" is returning 1 result <Rom-T>

---

src/test/java/pages/browse_languages/BaseAbcPage.java
src/test/java/pages/browse_languages/languages/AlphaBetaPage.java
src/test/java/pages/browse_languages/letters/APage.java
src/test/java/pages/submit_new_language/SubmitNewLanguagePage.java
src/test/java/tests/browse_languages/languages/AlphaBetaTest.java
src/test/java/tests/submit_new_language/SubmitNewLanguageTest.java

RF POM Add AlphaBetaNavigationTest
https://trello.com/c/zpm9ow54

[RF][Structure][POM][AlphaBetaPageTest][Navigation]<Asel>

---

src/test/java/tests/browse_languages/languages/LanguageAlgol601367Test.java
src/test/java/tests/browse_languages/letters/ATest.java

AT -  https://trello.com/c/hbuv1VNr/887-atstructureabcpagelanguagealgol601367
US - https://trello.com/c/dAbnBBgi/886-usstructureabcpagelanguagealgol601367

AT/Created LanguageAlgol601367Test and deleted test in ATest

---

src/test/java/pages/guestbook/SignV2Page.java

RF - https://trello.com/c/mNQG4vXl/897-rfsignv2pagerefactoring-pageirenesnitko

[RF][SignV2Page]Refactoring page<IreneSnitko>

---

src/test/java/pages/browse_languages/letters/IPage.java
src/test/java/tests/browse_languages/letters/ITest.java

https://trello.com/c/Lw6yqgLV/905-rfipagedelete-unused-methodssabinasaad

[RF][IPage][ITest]delete unused methods<sabinasaad>

---

src/test/java/pages/top_lists/BaseTopListPage.java
src/test/java/pages/top_lists/NewCommentsPage.java
src/test/java/tests/top_lists/NewCommentsTest.java
src/test/java/tests/top_lists/TopListNewLanguagesThisMonthTest.java
src/test/java/tests/top_lists/TopListRealTest.java
src/test/java/tests/top_lists/TopListTest.java
src/test/java/tests/top_lists/TophitsTest.java
src/test/java/tests/top_lists/ToplistAssemblyTest.java
src/test/java/tests/top_lists/ToplistEsotericTest.java

NewCommentsPageBaseTopListPageTopListTestTophitsTestToplistAssemblyTestToplistEsotericTest method  name changed
https://trello.com/c/B4YaToIX/909-rfnewcommentstestrefactordmswlpk

[RF][NewCommentsTest]Refactor<dmswlpk>

---

src/test/java/pages/MainPage.java
src/test/java/pages/guestbook/BaseGuestbookPage.java
src/test/java/pages/guestbook/GuestbookMenuPage.java
src/test/java/pages/guestbook/GuestbookV2Page.java
src/test/java/tests/guestbook/GuestbookV2Test.java

https://trello.com/c/OfHIHqyD/915-rftask-name
[RF][GuestbookV2] Refactored Guestbook_ReadGuestbook_LastPage_08AlimDuiL_Test
Большой рефакторинг. 
Создала страницу [GuestbookMenuPage], чтобы можно было создать объект в [MainPage] абстрактной страницы [BaseGuestbookPage]. 
В [BaseGuestbookPage] перенесла локаторы и методы из [GuestbookV2Page]. 
В GuestbookV2Test добавила три теста и поправила первый.
Старый класс  Guestbook_ReadGuestbook_LastPage_08AlimDuiL_Testиз to_do  пока не удалила. Есть вопросы.

[RF][GuestbookV2] Refactored Guestbook_ReadGuestbook_LastPage_08AlimDuiL_Test

---

src/test/java/pages/MainPage.java
src/test/java/pages/guestbook/GuestbookMenuPage.java
src/test/java/pages/guestbook/GuestbookV2Page.java
src/test/java/tests/guestbook/GuestbookV2Test.java
src/test/java/tests/guestbook/SignV2Test.java
src/test/java/tests/main/NavigationTest.java

https://trello.com/c/xsrDUJ5P/918-rfguestbookv2-refactored-guestbookv2test
[RF][GuestbookV2] Refactored GuestbookV2Test
Разобралась в наследовании. Удалила GuestbookMenuPage. Поправила тест GuestbookV2Test.

[RF][GuestbookV2] Refactored GuestbookV2Test

---

src/test/java/tests/browse_languages/languages/KotlinTest.java

[RF] https://trello.com/c/d3P8Pndo/924-rfstructuretestto-domoving-class-katytbrowselanguagestest-from-to-do-to-actual-class-galakon
KotlinTest is created. testSwitchToLoginPageReddit is moved to KotlinTest. KatyTBrowseLanguagesTest is deleted

[RF][Structure][test][to do]Moving class KatyTBrowseLanguagesTest from "to do" to actual class

---

src/test/java/tests/search_languages/SearchLanguagesTest.java

https://trello.com/c/e8TKXsPK/882-atsearchmainform-verify-empty-search-is-returning-0-results-svetlanag1011

[AT][Search][main][form] Verify empty search is returning 0 results

---

src/test/java/pages/browse_languages/BaseAbcPage.java
src/test/java/pages/browse_languages/letters/GPage.java

US  https://trello.com/c/zhXy8YHy/926-usstructuregpage-create-gpage-with-methods-locator-driver
AT  https://trello.com/c/xvqRnKqQ/927-atstructuregpage-create-gpage-with-methods-locator-driver-morigor

[AT][Structure][GPage] Create GPage with Methods, Locator, Driver <Morigor>

---

src/test/java/pages/guestbook/SignV2Page.java
src/test/java/tests/guestbook/SignV2Test.java

RF - https://trello.com/c/0xHOLdIs/930-rfsignv2testsignv2pagecommented-out-tests-and-methodsirenesnitko

RF/Commented Out Tests And Methods/<IreneSnitko>
